### ISSUE TITLE
User-defined decorator annotations

### ISSUE THREAD

**Issue by trustin** [line/armeria#1010]
Currently, a user has to define a class with a default constructor to specify a decorator on an annotated service:

```java
public class MyService {
    @Decorator(MyDecorator.class)
    @Get(...)
    public HttpResponse someMethod(...) { ... }
}
```

It would be great if a user can define his or her own decorator annotation, e.g.

```java
@Decorator(MyDecoratorFactory.class)
@interface MyDecorator {
    String foo();
    String bar();
}

public class MyService {
    @MyDecorator(foo = "f", bar = "b")
    @Get(..)
    public HttpResponse ...
}

public class MyDecoratorFactory implements Supplier<Function<Service<..>, Service<..>>> {
    public MyDecoratorFactory(MyDecorator annotation) {
        ...
    }
}
```

Armeria itself could also make use of this feature to provide an easy access to its decorators such as `LoggingService` and `ThrottlingService`.

/cc @hyangtack

**Comment by hyangtack** [comment]
I think it's good idea but it has some limitation because Java annotations only accept primitive types, String, Class, Enum, .. as its member. How about this?

- Introduce a factory to instantiate a new decorator with the given 'delegate' (e.g. a factory method like `Function<Service<..>, Service<..>>`)
- Pre-create a factory map via `ServerBuilder` with a name as its key and a factory instance as its value
- A user write their annotated http service class as follows:
```
public class MyService {
    @DecoratorFactory("myDecoratorFactory1")
    @Get(..)
    public HttpResponse ...
}
```
- Decorate the service method with a decorator created by the specified factory "myDecoratorFactory1"

**Comment by trustin** [comment]
Doesn't it defeat the original purpose of this issue - ability to define a custom annotation? How can a user create a custom annotation and pass parameters to his/her decorators in an annotated service class?

**Comment by hyangtack** [comment]
I thought you filed this issue to find a way of reusing our existing decorator like `LoggingService`. Also, I thought that a custom annotation is one of the way to do it. So I focused on how to use the existing decorators in annotated service easily. If the original purpose of this issue is to define a custom annotation, we need to implement your suggestion first. :-)

**Comment by hyangtack** [comment]
I think we can implement like below: 
```
    @Decorator(MyDecoratorFactory.class)
    @interface MyDecorator {
        String foo();
        String boo();
    }

    interface DecoratorFactoryFunction<T> {
        Function<Service<HttpRequest, HttpResponse>,
                Service<HttpRequest, HttpResponse>> newDecorator(T arg);
    }

    class MyDecoratorFactory implements DecoratorFactoryFunction<MyDecorator> {
        @Override
        public Function<Service<HttpRequest, HttpResponse>,
                Service<HttpRequest, HttpResponse>> newDecorator(MyDecorator arg) {
            return null;
        }
    }
```
Also I think that it would be better to have pre-defined factory instance pool because a user may want to inject their other object to be used in the decorator. WDYT?

**Comment by trustin** [comment]
SGTM :-)
