### ISSUE TITLE
Deprecation of HttpResponseWriter.respond() leads to verbose code

### ISSUE THREAD

**Issue by trustin** [line/armeria#1070]
For example, with the current API:

```java
private HttpResponse doPost(ServiceRequestContext ctx, HttpRequest req) {
    CompletableFuture<HttpResponse> future = new CompletableFuture<>();
    ctx.blockingTaskExecutor().execute(() -> {
        ...
        future.complete(HttpResponse.of(HttpStatus.OK));
    });
    return HttpResponse.from(future);
}
```

Before deprecation:

```java
private HttpResponse doPost(ServiceRequestContext ctx, HttpRequest req) {
    HttpResponseWriter res = HttpResponse.streaming();
    ctx.blockingTaskExecutor().execute(() -> {
        ...
        res.respond(HttpStatus.OK);
    });
    return res;
}
```

Obviously, the former would be more efficient because it uses an optimized version of `HttpResponse`, but it looks more verbose than the latter. What could we do to improve this?

/cc @anuraaga @imasahiro @kojilin

**Comment by trustin** [comment]
When `DererredHttpResponse` was not deprecated, we did this, which has less level of indirection:

```java
private HttpResponse doPost(ServiceRequestContext ctx, HttpRequest req) {
    DeferredHttpResponse res = new DeferredHttpResponse();
    ctx.blockingTaskExecutor().execute(() -> {
        ...
        res.delegate(HttpResponse.of(HttpStatus.OK));
    });
    return res;
}
```

Although this isn't ideal either, it's slightly less verbose and more efficient than the first example.

**Comment by trustin** [comment]
Perhaps this could get better if we add some more methods to `DeferredHttpResponse` (and maybe to `HttpResponseWriter` as well?):

```java
private HttpResponse doPost(ServiceRequestContext ctx, HttpRequest req) {
    DeferredHttpResponse res = HttpResponse.deferred();
    ctx.blockingTaskExecutor().execute(() -> {
        ...
        res.close(HttpStatus.OK);
    });
    return res;
}
```

**Comment by minwoox** [comment]
The last example looks good to me . 👍

**Comment by minwoox** [comment]
I was the one who was insisting that we need those APIs after deprecating the `HttpResponseWriter.respond(...)`. Because I feel that it's not convenient and a little verbose to implement the logics when we need to return the `Future` first and complete it later.
After thinking about it a little bit more, I kinna agree that we might not need them which can be more loads to our clients.
I'm still not sure which way is a better way. But if it ends with not adding those APIs, I hope to add the very first example to the javadoc so that our clients can adopt more easily :-)

**Comment by trustin** [comment]
Let me close this.
