### ISSUE TITLE
Better interop with load balancers

### ISSUE THREAD

**Issue by trustin** [line/armeria#1077]
- Support for `x-forwarded-for` (and related) headers in the core API
- Support for HAProxy protocol

**Comment by hyangtack** [comment]
We added [ServiceRequestContext#proxiedAddresses](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java#L253) [here](https://github.com/line/armeria/pull/1101) . So we can use it for handling `x-forwarded-for` and related headers.

If there's `xff` header, the first IP of it will be a client IP regardless whether PROXY protocol is used. Because the HAProxy is the last hop.
So, we can find a client IP as follows:
- If `xff` (or something) header exists, find a client IP from that header.
- If no `xff` header exists but PROXY protocol is used, a source IP in the PROXY protocol header will be a client IP.
- If none of them exists, a remote address of the channel will be a client IP.

**Comment by hyangtack** [comment]
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
- Forwarded: https://tools.ietf.org/html/rfc7239#section-4

How to handle when both headers exist in a request together?

**Comment by hyangtack** [comment]
How about:

- Adding a method which returns a client IP to [ServiceRequestContext](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java), such as:
```
/**
 * Returns the client address who initiates this request.
 */
<A extends SocketAddress> A clientAddress();
```
- Determining a client address with the following order:
  - If `Forwarded` header exists, the first `for` token of the header is picked.
  - If `X-Forwarded-For` header exists, the first address of its value is picked.
  - If [ServiceRequestContext#proxiedAddresses](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java#L253) is not `null`, its `sourceAddress` is picked.
  - Otherwise, [ServiceRequestContext#remoteAddress](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java#L53) is picked.

Questions:
- Is it reasonable that `Forwarded` has higher priority? I assumed that a proxy, which can handle `Forwarded` header, may translate `X-Forwarded-For` header to `Forwarded` when it adds its address to the request. If it didn't perform transition, (maybe) it should add its address to `X-Forwarded-For` header instead of adding a new `Forwarded` header. Does it make sense?
- Do we need to provide a list of whole addresses that a request has passed through? If so, we need to change the method signature.
