### ISSUE TITLE
Add Endpoint.ipAddr()

### ISSUE THREAD

**Issue by trustin** [line/armeria#1087]
Currently, `Endpoint.host()` is used as a hostname or an IP address of an endpoint. This does not work well for the `Endpoint`s whose IP addresses are known already. For example, let's say we want to use `DnsServiceEndpointGroup` with the following SRV records:

```
_https._tcp.foo.com. 3600 IN SRV 10 100 443 one.foo.com.
_https._tcp.foo.com. 3600 IN SRV 10 100 443 two.foo.com.
_https._tcp.foo.com. 3600 IN SRV 10 100 443 three.foo.com.
```

Because the client will have to create a TLS connection with proper SNI settings, the `Endpoint` should provide `foo.com` as the host name and provide `<the IP address of {one,two,three}.foo.com>` as the IP address of `foo.com`, which is not possible with our current API.

To make this possible, we would also improve `DnsServiceEndpointGroup` to send A/AAAA queries for the host names in the `SRV` records.

What do you think, @anuraaga?

**Comment by trustin** [comment]
Classes that need changes:

- `Endpoint`
- `PoolKey`
- `HttpClientDelegate`
- `HttpSessionChannelFactory`

**Comment by anuraaga** [comment]
Ah - yeah I did think about this a little but figured it wouldn't be necessary, obviously I didn't think about SNI though. Being able to specify both host and IP for a resolved endpoint sounds good. I'm not sure if we need to modify `DnsServiceEndpointGroup` to send the A queries since they'd be resolved using the normal DnsResolver either way, AFAIU.

**Comment by trustin** [comment]
Cool. Let me send a PR this or next week.
