### ISSUE TITLE
Why not expose CompletableFuture directly instead of a new abstract AsyncMethodCallback?

### ISSUE THREAD

**Issue by GrapeBaBa** [line/armeria#112]
Hi team,

I have a question about async invocation. Now there are a lot of reactive abstract interface for async invocation such as RxJava, CompletableFuture and so on. Why create a new abstract AsyncMethodCallback and it is a callback interface?

**Comment by anuraaga** [comment]
Armeria is designed to be completely compatible with the official Apache Thrift library, including the generated code for services, so that you can drop it in as-is to an existing thrift server / stubs artifact. We agree, though, that the thrift generated code is not really ideal in many aspects, and would like to at some point tweak the thrift compiler to generate more modern Java code. But as you can imagine, this is not a trivial task.

In the meantime, it's usually not so difficult converting between futures, other futures, and even callbacks and hopefully doesn't cause too much stress. Perhaps we could consider adding an adapter between CompletableFuture and AsyncMethodCallback at least though since it's in the JDK.

```java
class FutureUtils {
  void setFutureResult(CompletableFuture<T> future, AsyncMethodCallback handler) {
    future.whenComplete((result, throwable) -> {
      if (throwable != null) {
        handler.onError(throwable instanceof Exception ? (Exception) throwable : new ExecutionException(throwable);
      } else {
        handler.onComplete(result);
      }
    }
  }
```

Though I'm not sure if it's all that useful.

**Comment by trustin** [comment]
Filed a new issue: #113
