### ISSUE TITLE
Add a ResponseConverterFunction for RxJava Observables

### ISSUE THREAD

**Issue by trustin** [line/armeria#1342]
.. so that a user can return an `Observable` of a single element (or a list of elements?)

We may also want to implement some automatic registration mechanism for `ResponseConverterFunction`s so that the `Observable` converter is automatically added to the default converter list using SPI.

**Comment by hyangtack** [comment]
I think that we can make a converter for `Publisher` and `Observable` with the following specifications:
- If a single object is returned by `Publisher` (ex. `Mono.just(obj)`), try to convert the returned object by the registered converters when `onComplete` is invoked. 
- If multiple objects are returned by `Publisher` (ex. `Flux.fromArray(arr)`), collect the returned objects as a list then try to convert the list when `onComplete` is invoked.
- The conversion for the streaming response is unsupported. 

I think it's too complicate to convert streaming response because we might introduce a new interface like `StreamingResponseConverter`. So it would be simpler to handle the streaming response by a user.

Please let us know what you think about this issue. :-)
/cc @kojilin @imasahiro
