### ISSUE TITLE
Don't use Netty's GlobalEventExecutor for events because it's nulling out the ClassLoader

### ISSUE THREAD

**Issue by rkapsi** [line/armeria#1378]
Starting with Armeria 0.7.0 and the introduction of the StartStopSupport change in particular I've run into the problem that the start event is fired on the GlobalEventExecutor thread which has its "Context ClassLoader" (see this change https://github.com/netty/netty/commit/63bae0956aeb42e875ad303a2281989ad92acbf2) nulled out. This causes problems down the road if you're trying to do something on the event thread that requires the ClassLoader.

**Comment by trustin** [comment]
Thanks for reporting. We should probably just use a `ForkJoinPool.commonPool()` by default and allow a user override the default when calling `Server.start()` or `stop()`. What do you think?

**Comment by trustin** [comment]
It seems like we were using `GlobalEventExecutor` where necessary in our previous `Server` implementation: https://github.com/line/armeria/blob/armeria-0.69.0/core/src/main/java/com/linecorp/armeria/server/Server.java That is, you just were lucky enough to hit that branch; it can always happen when you start or stop a server simultaneously.

Using `ForkJoinPool.commonPool()` wouldn't help either because it seems to have a similar security mechanism built-in to prevent a class loader leak.

Let me:

- Keep using `GlobalEventExecutor` by default.
- Allow a user specify an `Executor` for start/stop tasks using `ServerBuilder.startStopExecutor()`.

**Comment by rkapsi** [comment]
@trustin: Thanks, that fixes our problem as well.
