### ISSUE TITLE
CompletableFuture composition is expensive due to CompletionException.fillInStackTrace()

### ISSUE THREAD

**Issue by trustin** [line/armeria#1426]
https://gist.github.com/trustin/52c5014a04331cf4c6a452e2cd6880b3 shows that `CompletionException.fillInStackTrace()` is taking 4-5% of samples.

`CompletionException` is instantiated when your callback is added to a child `CompletableFuture` of another future. See https://stackoverflow.com/questions/49230980/does-completionstage-always-wrap-exceptions-in-completionexception for more information.

Unfortunately, it is very hard to fix this problem because of the two reasons:

First, `CompletableFuture.encodeThrowable()`, which wraps an exception with a new `CompletionException` is a static package-local method that's not overridable.

```java
// From OpenJDK 10
static AltResult encodeThrowable(Throwable x) {
    return new AltResult((x instanceof CompletionException) ? x :
                         new CompletionException(x));
}
```

Second, even if we extend `CompletableFuture`, we have no control over what `CompletableFuture` instance is returned when future is chained. This is possible since Java 9, but our minimum requirement is Java 8. And the first problem is still not solved.

```java
OurCustomCompletableFuture f = ...;
// We can't make this return OurCustomCompletableFuture. It's always CompletableFuture.
CompletableFuture child = f.whenComplete(...); 
```

There are a few options for fixing this.

1. Implement our own `CompletionStage` implementation similar to `CompletableFuture`.
2. Consider adopting Reactor Core again. Replacing `StreamMessage` with `Flux` would
   - offload us from stream-related optimization to some extent
   - enable easier integration with other projects that rely on Reactor Core, reducing the cost of building adapters, etc.
   - provide rich stream manipulation capability of Reactor Core to our users
   - .. at the cost of huge refactoring or at the risk of getting worse performance.
   - Previous discussion: https://github.com/line/armeria/issues/970

**Comment by minwoox** [comment]
I was very surprised that the completion attached to the child receives a `CompletionException` wrapping the original `Exception` because that's totally different what I learnt from the javadoc.
Anyway I tried to find out the cases which a callback is added to a child `CompletableFuture` in the gRPC module, but I couldn't.
Instead I'm kind of suspicious of [this](https://github.com/line/armeria/blob/d7f7649b2297b4ba17558dbde3ff296cbd66e9dc/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java#L172-L193).
In `framer.writePayload(message)` throws an `Exception`, but there's no catch so CompletionException wraps the thrown exception because it's executed in `whenComplete()`.

**Comment by minwoox** [comment]
Please ignore the comment above. I have tested several times to remove the `CompletionExeption` by catching exceptions in the callback but the result was same as usual :(

**Comment by minwoox** [comment]
By the way, I found a case that using child `CompletionFuture` which is created from the root `CompletionFuture` by calling `whenComplete()` [here](https://github.com/line/armeria/blob/579bb5cf309dff705b87012d8cadf810f18f400d/core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java#L235-L238).
Perhaps we can just do `this.future = stopFuture;` (not creating a new future.)
