### ISSUE TITLE
DNS error with certain DNS servers that don't handle EDNS

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1512]
Only on Windows, I often am unable to resolve DNS with Netty

```
Caused by: java.net.UnknownHostException: failed to resolve 'www.googleapis.com' after 3 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
        ... 32 more
```

Despite `nslookup www.googleapis.com` for example working fine.

This happens both when invoking commands from the command line in an `msys2` terminal as well as in IntelliJ.

Don't have much else to go on, any recommendations on how I can get some more logs or something to help debug?

**Comment by anuraaga** [comment]
Here's what a change in Netty might look like - https://github.com/netty/netty/compare/4.1...anuraaga:retry-without-opt?expand=1

**Comment by trustin** [comment]
Hmm, without EDNS, we are clipped out at 512-byte boundary which is too small in many cases, so I expect most users will not want to disable EDNS. I agree with you though that we need to expose more configuration options. Given the large number of configuration options (see `DnsNameResolverBuilder`), it'd be better adding a configuration property like `Consumer<DnsNameResolverBuilder>` (or `Function`) instead of all individual options. What do you think? It should be way simpler than `ClientFactory.addressResolverGroupFactory()`. (We could even deprecate it.)

**Comment by anuraaga** [comment]
Yeah we definitely shouldn't disable it by default. The `Consumer` pattern looks great. Just wondering though, what do you think about the idea of having Netty retry if EDNS is enabled but the query fails?

**Comment by trustin** [comment]
I think it is fine as long as there's a way to tell the query failure was due to the OPT record. Can we?

**Comment by anuraaga** [comment]
Unfortunately not, it would be a bit of a heuristic. We can know if the server rejected the query as a "bad request" (`FormError(1)`) which may or may not be explicit enough for us, not sure.
