### ISSUE TITLE
spring boot without flux

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1518]
I was looking through armeria-spring-boot-webflux-autoconfigure and it seems there are hard dependencies (at least in the pom) on flux. I don't expect us to use flux in Zipkin as it brings in a chain of (sometimes unstable) dependencies we don't need.

We'd likely just use armeria's annotations I think, as it is just a few simple read endpoints and also the write would likely be custom anyway.

Maybe I can try excluding, but it seems primarily we'd want to have the option of armeria-spring-boot without flux

https://github.com/openzipkin/zipkin/issues/2331

**Comment by adriancole** [comment]
ex this is the sort of api we'd almost surely use for our read endpoints: https://github.com/line/armeria/blob/master/examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloAnnotatedService.java

**Comment by trustin** [comment]
You don't really need to pull `armeria-spring-*` at all if you do not want to integrate with Spring Web(flux). Armeria's annotated services work without Spring framework because it has its own annotation scanner, i.e. You can just define a bean which provides an Armeria `Server` and that should be all:

```java
@Configuration
public class ZipkinServerConfiguration

    @Bean
    public Server createServer() {
        final Server server = new ServerBuilder()...build();
        server.start().join();
        return server;
    }
}
```

Note that `Server` is `Closeable` so it will be shut down properly when application context is cleaned up.

**Comment by anuraaga** [comment]
One reason to want to use spring-boot might be it's configuration system. Not sure how committed zipkin-server is to maintaining the same configuration file format. Just for reference, though, I use typesafe config in non-spring armeria servers https://github.com/lightbend/config

**Comment by anuraaga** [comment]
I think the reason this integrates with flux is since it's Spring's API for integrating without servlet API available rather than anything reactive. Alternatively, armeria can use tomcat to provide the service API and work with spring without flux.

Thinking about it, I wonder if `spring-context` works without servlet API. If it does, then I guess the important bits of spring boot like the config should work without flux or tomcat. I've never tried such a configuration before though, I've only seen armeria + tomcat + spring or armeria ( flux + spring.

**Comment by trustin** [comment]
Does the new example at #1519 answer your question, @adriancole ?

**Comment by adriancole** [comment]
I think so. I will rework my local stuff with the above example which is a
more direct way I think. at any rate any other improvements could be
different issues.

**Comment by trustin** [comment]
Thanks! Let me stay tuned for further questions.
