### ISSUE TITLE
Why armeria run all grpc service logic directly in the event loop? 

### ISSUE THREAD

**Issue by iEAmi** [line/armeria#1524]
I have plan to convert all my grpc service to armeria-grpc but i have an issue, armeria execute service logic directly in event loop and i should handle blocking part manually, this take a lot of from me.
Now want to now what is your reason for using event loop for execute service logic?

Thanks and sorry for my bad english.

**Comment by trustin** [comment]
Thanks @iEAmi and @anuraaga for suggestion and fix. :+1:

**Comment by iEAmi** [comment]
Thanks for this new option 👍. You save my life 😁
 I am an armeria fan. Armeria is awsome

**Comment by trustin** [comment]
@iEAmi I'm happy to hear that you are enjoying Armeria in your project! What kind of service did you build using it? What pros and cons did you find from Armeria? Do you use it in production? If so, for what company? :smile:

**Comment by iEAmi** [comment]
We are working on a fintech project in 'Poolito' (mean Money in persian) and using armeria for exposing grpc/rest api to clients, android, ios, web.
Armeria built-in unframed-grpc and grpc-web and simple decorating api help us to use a single method for all kind of requests.
Learning armeria is easy، our developers learn to use armeria in less than a day and start writing code. 
Some part of our services now work on armeria in production. We have a plan to convert all services to armeria.

**Comment by trustin** [comment]
That's awesome! Please feel free to let us know if you find any missing features or shortcomings. We'd be happy to address them. :bowing_man: Cheers!

**Comment by iEAmi** [comment]
When I am using **useBlockingTaskExecutor** on **GrpcServiceBuilder** sometimes a problem occur.
client receive **INTERNAL: Half-closed without a request**.
I figure it out that problem can be from **ArmeriaSeverCall**, because **endOfStream** method invoked before **messageRead** and this make problem.
I think race occur between  threads.

**Comment by anuraaga** [comment]
Thanks for the report and sorry for the issue it does seem easy to run into.

@trustin what do you think of making blocking executor an EventLoopGroup? I haven't thought of it in detail but I think a large separate event loop group allows running blocking logic while also allowing pulling out a single event loop so for cases like this all callbacks run on the same (non-I/O thread) in order.

**Comment by anuraaga** [comment]
It's not about the server code but the requests from the client - so it's about which thread is used by the framework, not user. `ArmeriaServerCall` has never had any dependencies on what thread is used by user code.

The data from the client will come as message, then end of stream. We notify the callbacks for message and end of stream using the blocking executor, which means end of stream may have its callback run first if they're different threads, which isn't allowed. Ordering of callbacks is well defined.

I guess it's pretty normal for a blocking server to handle each incoming request on a separate dedicated thread (hence # of threads = number of concurrent requests), so running all callbacks for a given stream on the same non-I/O thread seems natural. The simplest way to implement it is taking advantage of `EventLoop` I think, otherwise a `Queue` with flushing could be used - but that's an event loop I think ;)

**Comment by trustin** [comment]
Thanks for explanation. I'd prefer `blockingTaskExecutor` to stay as `Executor` to give users more freedom although it would complicate the fix in this case...

**Comment by anuraaga** [comment]
Ah I forgot users can set `blockingTaskExecutor` too :) Will try to fix it with a `Queue` then. I think it's similar to grpc-java.

**Comment by trustin** [comment]
Thanks, @anuraaga :-)

**Comment by minwoox** [comment]
While I'm working on a 1.0 issue which is "Make a `blockingTaskExecutor` a `SchedulerExecutorService`", I remembered this issue came to my mind.

**Comment by minwoox** [comment]
I think it's worth to provide `blockingTaskExecutor` which runs the tasks in order when the tasks are provided from the same `EventLoop`. WDYT?

**Comment by trustin** [comment]
Yeah, we could provide an alternative executor implementation with such a feature, although I'm not sure if it has to be the default behavior. How about leaving this issue as closed, opening a new one and referring to this issue there? The original problem has been fixed already.

**Comment by minwoox** [comment]
Have thought about it and it was a bad idea that makes `blockingTaskExecutor` an `EventLoopGroup` because a user can specify his/her own executor and the thread pool never times out even when they are not used.
Thanks to @trustin, I can use `ScheduledThreadPoolExecutor` for "Make a `blockingTaskExecutor` a `SchedulerExecutorService`", so let me use that. 😄

**Comment by d3bt3ch** [comment]
> Thanks for explanation. I'd prefer `blockingTaskExecutor` to stay as `Executor` to give users more freedom although it would complicate the fix in this case...

Hello. I have started using `Armeria with Spring Boot` in a dev environment. I have a question related to `blockingTaskExecutor `. Why is `blockingTaskExecutor` a `ScheduledExecutorService` ?

**Comment by ikhoon** [comment]
`EventLoop` is `ScheduledExecutorService`. If `blockingTaskExecutor` supports `ScheduledExecutorService`, a flag(`useBlockingTaskExecutor`) could easily switch the two executors. Are there restrictions on `blockingTaskExecutor` being `ScheduledExecutorService`?
