### ISSUE TITLE
Allow unary grpc without google's library

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1703]
In zipkin server, we are often sensitive to version trees, and google's grpc library has some concerns around this including protobuf, guava, and recently things like opencensus also.

I'd love to be able to directly support two endpoints with no google grpc library dependency:
* grpc inbound unary call of storing a list of spans https://github.com/openzipkin/zipkin/pull/2328
* grpc outbound call to stackdriver https://github.com/openzipkin/zipkin-gcp/blob/master/storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverSpanConsumer.java

In the future, we can consider things like streaming etc, but it would be sufficient to cover the above, even only the inbound call.

The ideal integration would be either a hand-coded or armeria annotation markup grpc listener. Possibly this could be implemented by a new dependency "armeria-grpc-protocol" which doesn't include any google grpc deps and can allow you to receive a byte buffer of the upload and process as you see fit.

**Comment by trustin** [comment]
Do you expect this not to depend on `protobuf`?

**Comment by adriancole** [comment]
I'd love to not be able to, but I understand the method metadata may not be straightforward. For example, I personally only need 1 endpoint so if have a way to declare the method metadata directly would be able to opt-out of protobuf library dep.

**Comment by trustin** [comment]
> doesn't include any google grpc deps and can allow you to receive a byte buffer of the upload and process as you see fit.

I'm not sure I understood correctly, but isn't it already possible? What is different from handling an HTTP request stream as it is?

**Comment by adriancole** [comment]
@trustin sorry.. to be more specific, there are a number of types with dependencies on grpc library in armeria-grpc. Even if we excluded the grpc library dependency, there's no signature of `GrpcServiceBuilder` we could use (they accept io.grpc.BindableService). Perhaps a learning test could help if there's a way we can achieve the goal that I'm not thinking of..

**Comment by anuraaga** [comment]
Specifically, the idea is that logic related to headers, framer, and deframer, could be extracted for advanced users that want to use the gRPC wire protocol directly without the gRPC stubs. I think this isn't too invasive though depending on how far we go with it can possibly lead to some overkill too.

**Comment by trustin** [comment]
I see. Sounds like a good idea, although I'm not sure if we need to publish a dedicated artifact for this. Perhaps we could make it part of `armeria-grpc` and let an advanced user exclude `grpc-*` dependencies?

**Comment by adriancole** [comment]
that's ok with me. probably just need a classpath isolated test to ensure
it works (or manual testing)

**Comment by anuraaga** [comment]
Cool - in that case it will probably mostly be moving code out of internal into a protocol package. I think it's worth doing that first and then seeing whether it's worth adding small helpers like simple unary dispatchers for client / server.

**Comment by ejona86** [comment]
gRPC does not have a strong dependency on protobuf, only the stubs do. If you avoid grpc-proto and grpc-services then you should be protobuf-free.

It wouldn't take too much work to split a "grpc-api" out of "grpc-core". https://github.com/grpc/grpc-java/issues/1447 is a tracking issue for it. Although https://github.com/grpc/grpc-java/issues/1447 hasn't seen much activity, I do bring it up frequently with the team and drive designs based on it. With Bazel we build io.grpc separately, so it would be trivial to split into a separate artifact.

I will say I'm disappointed people have been having trouble with Guava _without telling us_. gRPC has downgraded Guava multiple times to help give time for the ecosystem to update. Guava has also gotten a lot better in terms of compatibility, in part due to feedback from grpc. Guava 20 was really the last hurdle, since the Preconditions changes finds all the places people have been downgrading Guava to make it work.

`io.grpc` should not be exposing Guava on its API surface (only grpc-stub does), so any references to Guava can be changed. The current imports of Guava in `io.grpc`:
```
import com.google.common.annotations.VisibleForTesting;
import com.google.common.base.Joiner;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.google.common.base.Preconditions;
import com.google.common.io.BaseEncoding;
import com.google.common.util.concurrent.ListenableFuture;
import static com.google.common.base.Charsets.US_ASCII;
import static com.google.common.base.Charsets.UTF_8;
import static com.google.common.base.Preconditions.checkArgument;
import static com.google.common.base.Preconditions.checkNotNull;
import static com.google.common.base.Preconditions.checkState;
import static com.google.common.base.Throwables.getStackTraceAsString;
```

Virtually all of those could be shaded (Preconditions) or avoided. It looks like the BaseEncoding dependency is trash; it's just for a toString(). ListenableFuture is used once in InternalInstrumented and this does seem like a case where Guava is exposed in an internal API, but it could be replaced with a callback API.

We don't want to shade much, since it does increase costs for Android. But this seems pretty manageable if there was a will for it to happen.

**Comment by adriancole** [comment]
Here is the integration we are working on. As this is a protobuf service, we do need some dependencies, but not all (for example, zipkin embeds its own protobuf codec). I think there are some deps that are unstable and unnecessary for what we are doing. That's why I feel it should be possible for armeria to handle some more work directly, mostly about creating the service descriptor and invoking the code associated with that.

https://github.com/openzipkin/zipkin/pull/2328

Here are the related deps, so far, besides the main protobuf-java library
```
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.6.1:compile
[INFO] |  |  +- com.google.guava:guava:jar:26.0-android:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.19.0:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.19.0:compile
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.19.2:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.19.2:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.19.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.19.0:compile
[INFO] |  +- io.grpc:grpc-services:jar:1.19.0:compile
[INFO] |  |  \- com.google.re2j:re2j:jar:1.2:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.19.0:compile
```

**Comment by ejona86** [comment]
If grpc-api was split from grpc-core, then grpc-api wouldn't depend on opencensus. Rewriting a fairly simple parser in grpc-services could also remove the re2j dep (it apparently started as a java.util.regex dep, but that implementation can be exponential in cases so it looks like it was replaced with re2j even though that's an overkill).

And FWIW, if you like undertow there is https://github.com/grpc/grpc-java/pull/4738 . It runs grpc server under servlet environment. It's POC because of limited feedback on API and I've had limited time since "build it and they will come" hasn't really been happening with it.

**Comment by adriancole** [comment]
> If grpc-api was split from grpc-core, then grpc-api wouldn't depend on
> opencensus. Rewriting a fairly simple parser in grpc-services could also
> remove the re2j dep (it apparently started as a java.util.regex dep, but
> that implementation can be exponential in cases so it looks like it was
> replaced with re2j even though that's an overkill).
>
This seems pretty sensible all around. Mainly a priority issue?

> And FWIW, if you like undertow there is grpc/grpc-java#4738
> <https://github.com/grpc/grpc-java/pull/4738> . It runs grpc server under
> servlet environment. It's POC because of limited feedback on API and I've
> had limited time since "build it and they will come" hasn't really been
> happening with it.
>
actually we are post-undertow :) thanks for the offer though. We (zipkin)
are working with armeria as it is more aligned in general with what we are
doing. We used to use undertow.

**Comment by ejona86** [comment]
> This seems pretty sensible all around. Mainly a priority issue?

Yeah. They are things we wanted to do, but with many other things that add/fix things that are directly impacting users... I sent out re2j removal in https://github.com/grpc/grpc-java/pull/5566 . The grpc-api split could maybe happen this week, although it'll be 5-6 weeks until it is released.

**Comment by ejona86** [comment]
Oh, and there is an issue to remove census from grpc-core. https://github.com/grpc/grpc-java/issues/5076 . There is quite a bit of will on the team to do this, but priorities...

**Comment by anuraaga** [comment]
Reading that issue, it sounds like census is only used if on the classpath - that doesn't sound so bad to me TBH.

I do want to clarify my thinking on the general dependency issues, which may not align with @adriancole since we're not the same human ;) When I saw a PR where he had a lot of fine tweaking of dependencies, I noticed that Guava is a common theme. Interestingly, I don't think gRPC caused any issues - I found a different library and filed an issue https://github.com/googleapis/gapic-generator/issues/2648#issuecomment-477656687

Since the artifact name includes gRPC, I think there is some mental correlation happening but I have seen the issues there downgrading guava, etc and don't see a huge issue. But shading it away so people have even less worries would make it even easier to be comfortable.

**Comment by adriancole** [comment]
Making some comments around Rag's to clarify my POV, but not to clarify his
POV.

> Reading that issue, it sounds like census is only used if on the classpath
> - that doesn't sound so bad to me TBH.
>
less a problem for us, except we need to explicity remove the deps. For
others, if someone wants to override census and the signatures change they
will conflict. Since we don't use census, I agree it is limited to the
extra deps problem which is something we track.

I do want to clarify my thinking on the general dependency issues, which
> may not align with @adriancole <https://github.com/adriancole> since
> we're not the same human ;) When I saw a PR where he had a lot of fine
> tweaking of dependencies, I noticed that Guava is a common theme.
> Interestingly, I don't think gRPC caused any issues - I found a different
> library and filed an issue googleapis/gapic-generator#2648 (comment)
> <https://github.com/googleapis/gapic-generator/issues/2648#issuecomment-477656687>
>
for zipkin we had to switch to guava 20something only to get grpc to not
complain. We did that to make stackdriver integration work downstream, so
that's a historical effort we did before and would prefer to not have to
track. We have another library that uses old guava and just plain lucky it
didn't conflict. So the zipkin us, yeah it hurt, but maybe not the armeria
us.

> Since the artifact name includes gRPC, I think there is some mental
> correlation happening but I have seen the issues there downgrading guava,
> etc and don't see a huge issue. But shading it away so people have even
> less worries would make it even easier to be comfortable.
>
agree especially the silly breaks around preconditions, if shaded could
have avoided some messes. I'm sure people accidentally add bytecode larger
than a private version of the preconditions :)

**Comment by adriancole** [comment]
there is a massive size difference, which I do think is almost completely unnecessary for us in zipkin. let's get this crankin! Anyone have cycles to do a completely google lib dep free means to invoke our endpoint which can parse its own message from bytes?

```bash
$ du -k zipkin-nogrpc.jar
47396	zipkin-nogrpc.jar
$ du -k  zipkin-grpc.jar
55840	zipkin-grpc.jar
```

diff zipkin-nogrpc.jars zipkin-grpc.jars
```diff
1a2
> 3277212 BOOT-INF/lib/byte-buddy-1.9.12.jar
9a11
> 1424558 BOOT-INF/lib/protobuf-java-3.7.0.jar
13a16
> 1200130 BOOT-INF/lib/proto-google-common-protos-1.12.0.jar
15a19
> 825158 BOOT-INF/lib/grpc-services-1.19.0.jar
16a21
> 766263 BOOT-INF/lib/grpc-core-1.19.0.jar
35a41
> 327600 BOOT-INF/lib/opencensus-api-0.19.2.jar
41a48
> 241622 BOOT-INF/lib/gson-2.8.5.jar
43c50
< 226228 BOOT-INF/lib/zipkin-2.12.9-SNAPSHOT.jar
---
> 226229 BOOT-INF/lib/zipkin-2.12.9-SNAPSHOT.jar
46a54
> 142031 BOOT-INF/lib/armeria-grpc-0.83.0.jar
51a60
> 126747 BOOT-INF/lib/re2j-1.2.jar
53a63
> 113966 BOOT-INF/lib/protobuf-jackson-0.3.1.jar
61a72
> 68840 BOOT-INF/lib/protobuf-java-util-3.6.1.jar
70a82
> 39549 BOOT-INF/lib/grpc-stub-1.19.0.jar
77a90
> 29016 BOOT-INF/lib/grpc-context-1.19.0.jar
89a103
> 14961 BOOT-INF/lib/opencensus-contrib-grpc-metrics-0.19.2.jar
91a106
> 13694 BOOT-INF/lib/error_prone_annotations-2.2.0.jar
98a114
> 7614 BOOT-INF/lib/grpc-protobuf-lite-1.19.0.jar
99a116,117
> 6834 BOOT-INF/lib/zipkin-proto3-0.2.0.jar
> 6684 BOOT-INF/lib/zipkin-collector-grpc-2.12.9-SNAPSHOT.jar
105a124
> 4994 BOOT-INF/lib/grpc-protobuf-1.19.0.jar
108a128
> 3448 BOOT-INF/lib/animal-sniffer-annotations-1.17.jar
109a130
> 2363 BOOT-INF/lib/zipkin-autoconfigure-collector-grpc-2.12.9-SNAPSHOT.jar
```

**Comment by anuraaga** [comment]
I have the interest and an idea of how to implement it in my head, but probably don't have the cycles until Fukuoka

**Comment by adriancole** [comment]
did some optimizations prior to the pending [zipkin 2.13](https://github.com/apache/incubator-zipkin/releases/tag/v2.13.0) which is being [voted on now](https://lists.apache.org/thread.html/9d4bbf52bd93a3907737b6cf445b5465607b7dd260a4bdc2a519e6ab@%3Cdev.zipkin.apache.org%3E)

end result is that with gRPC we are slightly smaller than last release :)

```
47168 zipkin.jar (2.12.9 with no grpc endpoint)
47164 zipkin.jar (2.13.0 with grpc endpoint)
```

thanks for all the help!
