### ISSUE TITLE
Is there any open-source project using armeria to refer?

### ISSUE THREAD

**Issue by whhan91** [line/armeria#1709]
I am writing a simple server program seeing https://line.github.io/armeria/server.html. And I would like to refer to another real project. Is there an open source project implemented with armeria to refer?

And is there any support for DB? and if not, is there any plan for support DB utils?

**Comment by trustin** [comment]
Hi! Thanks for asking a question. As far as I know there is no standalone open-source server product written on top of Armeria. However, there is a stack built on top of Armeria, called 'Curiostack': https://github.com/curioswitch/curiostack

We also have various closed-source projects that depend on Armeria both internally and externally. To list a few companies:

- [LINE](https://engineering.linecorp.com/) (ourselves)
- [Slack](https://slack.engineering/) (Check the slides at: https://grpconf19.sched.com/event/L715/grpc-for-the-thrifty-grpc-at-slack-josh-wills-slack)
- [Kakao Pay](https://www.kakaocorp.com/service/KakaoPay)
- [Infostellar](https://www.infostellar.net/)

> Is there any support for DB? and if not, is there any plan for support DB utils?

Armeria does not try to be full-stack. We believe there are a lot of great data access libraries in the market already, and it is our role to provide just enough amount of glue between Armeria and them. That's why we do not try to replace Spring framework but provide a better integration layer, unlike some other 'full stack' frameworks.

Because Armeria's request and response stream is compatible with Reactive Streams and Java `CompletableFuture`, it is already fairly easy to integrate with existing asynchronous/reactive data sources. For example, there are already asynchronous/reactive APIs for well known data sources such as Redia, HBase, Kafka, etc.

Please feel free to let us know if you have more questions regarding this topic.

**Comment by trustin** [comment]
And, you may fine the examples at https://github.com/line/armeria-examples useful. Please let me know what you think and what examples you'd like to see!

**Comment by trustin** [comment]
Updated the list because I completely missed out OpenZipkin server. Sorry, @adriancole :stuck_out_tongue_winking_eye:

**Comment by adriancole** [comment]
heh yep!

**Comment by whhan91** [comment]
Thanks for quick answer! All examples looks interesting, and code is perfectly simple. looks zipkin-server is what I want. Thank you very much!
