### ISSUE TITLE
A new load-balancing `EndpointSelectionStrategy` which increases weight gradually

### ISSUE THREAD

**Issue by trustin** [line/armeria#1757]
Some load balancers have a nice feature called 'slow start', which increases the load of a newly added node gradually so that the new node is given with some room for initial JIT and GC, e.g. Increase the weight from 1 to 1000 for the next 3 minutes.

We could provide a new `EndpointSelectionStrategy` implementation that provides such a feature. To achieve this, we need to:

- Listen to the removal and addition of an endpoint by adding a listener to `EndpointGroup` using `EndpointGroup.addListener()`.
- Find a fast algorithm that allows us to update the round-robin weight of many endpoints very quickly.
- Provide a customizable API that determines the weight of a new node based on when the node appeared, e.g. `BiFunction<Endpoint, Duration, Integer>` whose input is (the endpoint, the time passed since the node appeared) and output is the weight.

This strategy would be nice if paired with a dynamic endpoint group such as `HttpHealthCheckedEndpoint`. When a node which was previously unhealthy becomes healthy, the weight of the node will increase gradually.

**Comment by linxGnu** [comment]
@trustin I am afraid that right now I could not think of any effective algorithm for this case. Due to nature of weighted round-robin which care about priority of weight.

I will think about it and find one (think of some kind of tree, but it needs to be lightweight)

**Comment by linxGnu** [comment]
@trustin I am doing proposal for it. May I ask to get as details as possible here. Because it's very important to know all the cases while designing algorithm.

I have several questions for the new `EndpointSelectionStrategy`:

1. When selecting nodes, shall we still use weighted-round-robin strategy?
2. `Increase the weight from 1 to 1000 for the next 3 minutes.`, so we have an updater, routinely update weight (i.e, every 100ms)?
3. When adding a new node, its initial weight is 0?
4. We need to find `fast algorithm` not only `update` but also `select` endpoint `concurrently`?
5. About:
`Provide a customizable API that determines the weight of a new node based on when the node appeared, e.g. BiFunction<Endpoint, Duration, Integer> whose input is (the endpoint, the time passed since the node appeared) and output is the weight`
What is the purpose of the weight output. It's used to update node as question 2 mentions?

**Comment by trustin** [comment]
@linxGnu Thanks for your questions and sorry for a late reply.

> When selecting nodes, shall we still use weighted-round-robin strategy?

Yes.

> we have an updater, routinely update weight (i.e, every 100ms) of current all nodes?
> when updater stop? which trigger (all node weight is 1000)?

We routinely update the weight of the newly appeared nodes and each endpoint has its own target weight. For example, if we started with an empty endpoints:

1. Node A is newly added with weight 1000.
   - Endpoints: [A]
   - The weight of A increases from 0 to 1000 over a certain period (e.g. 10 minutes)
2. Node B is newly added with weight 500.
   - Endpoints: [A, B]
   - The weight of B increases from 0 to 500 over 10 minutes.
   - The weight of A continues increasing to 1000.
   - Node A reaches at its peak weight (1000) before node B reaches its peak weight (500) because it started slow-start process earlier, i.e. increment is not an absolute value but a ratio.
3. Node A is removed and then added back with weight 700.
   - Node A starts the slow-start process from weight 0 again, up to 700.

> When adding a new node, its initial weight is 0?

Yes.

> We need to find fast algorithm not only update but also select endpoint concurrently?

Yes, but if we have to trade off, we should choose selection performance and reduce the frequency of weight updates.

> What is the purpose of the weight output. It's used to update node as question 2 mentions?

Usually, a user will expect the weight to increase linearly, but a user may want non-linear increment by specifying a custom function. Does it make sense?

**Comment by linxGnu** [comment]
@trustin thank you very much for very detailed answer. I understand the behavior now.

According to one of your answer: `increment is not an absolute value but a ratio`:
- at least for now, I could not find any suitable algorithm for our case

So I guess your suggestion `reduce the frequency of weight updates` is good enough:
- currently, weighted round-robin requires sort-and-prepare items before use. If total number of item is 10K for example, then this op is very fast (around 0.001s, my local benchmark).

Therefore, I think we could wait for: https://github.com/line/armeria/pull/1764

I am sorry because not able to find a good algorithm now.

**Comment by trustin** [comment]
Thanks for a reply. @linxGnu. Let's continue reviewing #1764 then. :wink:
