### ISSUE TITLE
Using armeria grpc client in spring mvc can't propagate trace context

### ISSUE THREAD

**Issue by alex-lx** [line/armeria#1767]
We have a spring-mvc application. It uses spring-cloud-sleuth for distributed tracking. We also use Ameria's Client to call our backend Ameria Grpc service.

Expect:
Tracing should work good, Ameria's client should use the same trace of spring mvc's request.

But in fact:
Ameria's client create a new trace.

More info:

some code:
```java
    @Bean
    RecommendServiceGrpc.RecommendServiceBlockingStub recommendServiceBlockingStub(
            Tracing tracing
    ) {

        return new ClientBuilder("gproto+http://group:ai-recommend-v2/")
                .decorator(HttpTracingClient.newDecorator(tracing))
                .build(RecommendServiceGrpc.RecommendServiceBlockingStub.class);
    }
    @Bean
    CurrentTraceContext.Builder sleuthCurrentTraceContextBuilder() {
        return RequestContextCurrentTraceContext.newBuilder();
    }
```

warning in log:
```
2019-05-14 15:35:50.425  WARN [,,,] 34541 --- [nio-8081-exec-1] .a.c.t.RequestContextCurrentTraceContext : Attempted to propagate trace context, but no request context available. Did you forget to use RequestContext.contextAwareExecutor() or RequestContext.makeContextAware()?
```

We tried to customize the executor of tomcat, but the application would throw RequestContext unavailable when starting up.
```java
    @Bean
    WebServerFactoryCustomizer<TomcatServletWebServerFactory> tomcatServletWebServerFactoryWebServerFactoryCustomizer() {
        return new WebServerFactoryCustomizer<TomcatServletWebServerFactory>() {
            @Override
            public void customize(TomcatServletWebServerFactory factory) {
                factory.addConnectorCustomizers(
                        new TomcatConnectorCustomizer() {
                            @Override
                            public void customize(Connector connector) {
                                ProtocolHandler handler = connector.getProtocolHandler();
                                if (handler instanceof AbstractProtocol) {
                                    AbstractProtocol protocol = (AbstractProtocol) handler;
                                    protocol.setExecutor(
                                            RequestContext.current().makeContextAware(
                                                    protocol.getExecutor()
                                            )
                                    );

                                }
                            }
                        }
                );

            }
        };
    }
```

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: RequestContext unavailable
.....
Caused by: java.lang.IllegalStateException: RequestContext unavailable
	at com.linecorp.armeria.common.RequestContext.current(RequestContext.java:75) 
```

**Comment by anuraaga** [comment]
It sounds like you are using the normal spring-mvc tomcat server with an armeria client. Out of curiosity, have you thought about using armeria's native support for spring-mvc? Then the tracing should work without worrying about where the context is coming from, and you'd probably get better performance / HTTP/2 support for free.

https://github.com/line/armeria/tree/master/examples/spring-boot-tomcat

But in the case that spring is the server, it is setting up trace contexts while armeria's `RequestContextCurrentTraceContext` assumes armeria is setting up trace contexts. We usually use `RequestContext` for trace propagation since armeria code tends to be asynchronous and switch threads, and propagating the context in a single `ThreadLocal` often doesn't work. But I guess when adding an armeria client to a blocking server, this isn't a case that would happen much in practice. I think we can relax our current `ensureScopeUsesRequestContext` check to log instead of throw - for highly asynchronous servers, it would still be problematic not to use the request context state, but for simple blocking ones it could still work.

/cc @adriancole

**Comment by alex-lx** [comment]
Thanks for your response.
Yes, we could migrate this application to Armeria, however, It would be better if there's another solution without migrating because we have some other services, those maybe not easy to migrate.

**Comment by adriancole** [comment]
I agree with @anuraaga worth a try first.
