### ISSUE TITLE
Why not use protobuf-java-util for json Marshaller

### ISSUE THREAD

**Issue by RyouZhang** [line/armeria#1784]
Why not use protobuf-java-util for json Marshaller？
curioswitch can‘t print enum as int， and you can’t reflect to set jsonfactory codec do this，because curioswitch json Marshaller printe enum is hard code to get enum name.

**Comment by anuraaga** [comment]
`protobuf-jackson` is much faster than `protobuf-java-util` and is intended to allow using JSON in production, the reflection-based implementation in upstream would be very inefficient for that.

It seems that upstream has added a couple of knobs that need to be reintegrated into `protobuf-jackson` in a new version. But in the meantime, it does follow the protobuf json spec here with its defaults

https://developers.google.com/protocol-buffers/docs/proto3#json

Can you describe your use case more just to understand why the defaults don't work for you? Thanks.

**Comment by RyouZhang** [comment]
I want to use proto3 enum as int not string，protobuf-jackson can‘t support。

the printEnum method:

https://github.com/curioswitch/curiostack/blob/protobuf-jackson-0.3.1/common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/SerializeSupport.java

**Comment by anuraaga** [comment]
Yes but the spec I linked states that enum fields are serialized as names `The name of the enum value as specified in proto is used.`

`JsonFormat` has an option to serialize as ints, and that can easily be added to protobuf-jackson, but I'm wondering what your use case is that requires ints, which is not the default protobuf json behavior.

**Comment by RyouZhang** [comment]
Maybe armeria can support custom serialize forma, or relplace serialized provider.

**Comment by anuraaga** [comment]
https://github.com/line/armeria/pull/1786 will add support for printing enums as ints

I don't think we'll make the JSON marshaller pluggable, because in the end there is only one spec for JSON serialization of protobuf - https://developers.google.com/protocol-buffers/docs/proto3#json. Armeria has supported this since implementing JSON support, and any options language-specific libraries provide are nice-to-have for specific use cases, but that spec is the best we have for cross-language JSON marshalling of protobuf. We're always happy to add support for new features that e.g., `protobuf-java-util` adds, like we did here, but they'll be best effort considering all protobuf parsers should support that spec.

I'm still curious about your use case since I would expect the current defaults to work well in most situations. How are you parsing the JSON messages? If you're using a protobuf JSON parser, it should work fine with Armeria's defaults, if not I think it's a bug in that library and we should look there. If you're using a custom JSON parser, can't you control it so it follows that documented spec? If something prevents that, it's ok, and we'll try our best to add new features as needed, but it would be very helpful to know how you're dealing with the JSON payloads outside of Armeria to cover your use case.

**Comment by RyouZhang** [comment]
for example:

service experience{
    rpc Test1(google.protobuf.Empty) returns (Test1Reply);
}

enum TestStatus {
    UNKNOWN = 0;
    STATUS_A = 1;
    STATUS_B = 2;
}

message Test1Reply {
    string raw = 1; 
    TestStatus status_code = 2;
    google.protobuf.Int32Value value = 3;
}

then reply build:
        Test1Reply reply = Test1Reply
        .newBuilder()
        .setStatusCode(TestStatus.STATUS_A)
        // .setValue(Int32Value.newBuilder().setValue(999).build())
        .setRaw("hello world").build();

now I get json:
{"raw":"hello world","statusCode":"STATUS_A"}

A proto3 JSON implementation may provide the following options:
Emit fields with default values
Emit enum values as integers instead of strings

How to set Json Marshaller to do this??

**Comment by anuraaga** [comment]
With the current version of the code, you can set `includingDefaultValueFields` when setting up the `GrpcService` like

```
new GrpcServiceBuilder()
  .addService(...)
  .jsonMarshallerCustomizer(marshaller -> marshaller.includingDefaultValueFields(true))
```

In the next version of Armeria, you'll also be able to set `printingEnumsAsInts`.

Hope this helps.

**Comment by RyouZhang** [comment]
thanks
