### ISSUE TITLE
Propose a client side failover strategy

### ISSUE THREAD

**Issue by shelocks** [line/armeria#182]
For now,we have a client side load balancer,maybe we need a failover strategy to deal with the request failed.I have some candidate proposals:

1) Endpoint aliveness monitor
As @anuraaga mentioned in this [comment](https://github.com/line/armeria/pull/144#issuecomment-213025591),a aliveness monitor check endpoints's status and update endpoint group info(like set endpoint status to offline/online),the load balancer only select the alive endpoint.
Cons:can't ensure the current request success at last,because the monitor check interval

2)CircuitBreaker/EndpointGroupInvoker update endpoint status
In the ResultFuture,those class can update the endpoint's status to offline if the request failed,and the load balancer will only select the alive endpoint when next request is coming.
Cons:same as 1)

3)Catch the network exception when invoking,and select the next endpoint to continue the method request
The following code illustrates this point

```
public final class EndpointGroupInvoker extends DecoratingRemoteInvoker {
    ....

    @Override
    public <T> Future<T> invoke(EventLoop eventLoop, URI uri,
                                ClientOptions options,
                                ClientCodec codec, Method method,
                                Object[] args) throws Exception {
        for(int time=0;time<tryCount;time++){
            URI uri = selectedEndpoint();
            try {
                return delegate().invoke(eventLoop, uri, options, codec, method, args);
            }catch (NetworkException ex){
                //do some logging
            }
        }
    }
}
```

Pros:can ensure the request success  if the endpoint group has alive instance and the tryCount number is large enough.
Cons:the armeria is async,maybe catching the network exception in this way is not easy(need some sync test?) and has performance impact.

 @trustin @anuraaga , what do you think about these candidates,Thanks!

**Comment by trustin** [comment]
@shelocks wrote:
> what do you think about these candidates

(1, 2) and (3) are not mutually exclusive. In case of network issues, you can always retry for all proposed ideas.

> the armeria is async,maybe catching the network exception in this way is not easy(need some sync test?) and has performance impact.

Not really, you can just add a listener to the Future returned by delegate().invoke(...) and decide to retry there:

```java
Promise<T> promise = eventLoop.newPromise();
delegate().invoke(...).addListener(f -> {
    ...
    if (success or non-network failure) {
        promise.setSuccess/Failure(....);
    } else {
        retry();
    }
});
return promise;
```

**Comment by trustin** [comment]
@shelocks Also, (1) and (2) are not mutually exclusive either. A user might want to use both of them.

**Comment by anuraaga** [comment]
In general I'm not a fan of automatic retry because there's pretty much no way to know how far your request got when it failed, even due to ClosedSocketException or whatever. Pretty much the only network failure I'd be comfortable with retrying is if the inital bits never got sent over the wire in the first place - is this something we can distinguish (seems difficult in HTTP2)? Retrying in such a situation seems great if it's possible.

Also, DB stuck, full GC stuck, etc usually need to all be handled anyways, so handling network failure in the RPC layer but leaving other random failures up to the user seems not so useful.

It's of course ok to provide a RetryingClient in case users do have a use for 3), but IMO it's really only useful for read-only APIs, which limits its applicability a lot.

I'm not sure what the difference is between 2) and 3). Both seem to rely on request failure, which have the same issues of not knowing whether it's safe to retry.

1) is pretty much the only way I've seen to reliably do RPC. It has the problem with random network failures that you mention, but as I mentioned above, apps need to be able to handle random failure regardless. But it will allow for safe rolling restarts - armeria server already has support for graceful shutdown using the health endpoint. A simple implementation would poll the health path on all backends, a more complex (but scalable) implementation would poll an etcd or zookeeper file.

**Comment by trustin** [comment]
Agreed. Automatic retrial is only applicable in a very specific situation.

**Comment by trustin** [comment]
I guess this is pretty much solved by the `RetryingClient` written by @minwoox. Great to see your effort reaches the goal. 👍
