### ISSUE TITLE
Endpoint can't have SessionProtocol?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#1908]
While I'm working on https://github.com/line/armeria/pull/1886#discussion_r303707344, I thought `Endpoint` might be able to have `SessionProtocol`. By the definition in Wikipedia, an endpoint means [an interface exposed by a communicating party or by a communication channel](https://en.wikipedia.org/wiki/Communication_endpoint), so perhaps we can contain the `SessionProtocol` in it. If we do that, it will make some APIs cleaner and simpler, especially for https://github.com/line/armeria/pull/1886.

However, there are two things that I'm concerned:
- The two different `Endpoint`s are the same one eventually.
  - For example, the `SessionProtocol` `http` could be `h1c` or `h2c`. We have to deal with it specially.
- The `Scheme` contains `SerializationFormat` and `SessionProtocol`.
  - The builders for clients have methods that take `Scheme` and `Endpoint` together. We need to break up the `Scheme` and let the builders take `SerializationFormat` and `Endpoint`.
  - The same information resides in scheme and endpoint in the `ClientRequestContext`.
  - Because of this, I'm not sure this change is worth it.

**Comment by anuraaga** [comment]
I had a similar notion recently when setting up some `EndpointGroup` but decided it's probably not a good idea, since I think it's not safe if a client can use an endpoint group where the endpoints are a mix of secure TLS and insecure. While it could be possible to just validate this when creating an endpoint group, I find it intuitive that our `Endpoint` relates to TCP layer connection, and the session protocol on top of that is a separate concept. On the flip side, I do see the benefit for some APIs, and especially #1886.

**Comment by minwoox** [comment]
> endpoint group where the endpoints are a mix of secure TLS and insecure.

That's a good point. I couldn't think of that. 😅
So yeah, let's treat the `Endpoint` as it is.
