### ISSUE TITLE
HealthCheckedEndpointGroup should probably wait for connectTimeout before throwing exception.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1910]
Currently, `HttpHealthCheckedEndpointGroup` will throw an `EndpointGroupException` immediately when a request is attempted when there are no endpoints. It would be more intuitive and simpler to use if it was possible for the request to wait until `ClientFactory.connectTImeout()` before throwing the exception, allowing a health checked endpoint group to have similar connection behavior as just a single endpoint.

**Comment by trustin** [comment]
That's a good idea.

**Comment by trustin** [comment]
I guess we can implement this behavior like the following:

1. Define a dedicated exception that signifies there are no endpoints available.
2. Implement the delayed response somewhere in the beginning of client request execution path where the exception defined at (1) is caught.

**Comment by trustin** [comment]
That being said, I guess it may not affect our current API, which means we may be able to move this to post-1.0. What do you think, @anuraaga?

**Comment by anuraaga** [comment]
I agree this is just behavior change so can untarget 1.0

**Comment by trustin** [comment]
We have a related issue where `RetryingClient` does not work at all when an `EndpointGroup` is empty, because the request fails even before `RetryingClient` tries anything.

To let the request be handled by a decorator even if there's a chosen endpoint, we're gonna have to change when `ClientRequestContext.endpoint()` returns `null` and to decide at which point we need to wait until an endpoint is available - Wait at the beginning or the end of invoking a decorator chain? What should we do when `RetryingClient` is involved?

**Comment by trustin** [comment]
A related question from Andrey at Slack workspace:

> Hi guys, I use `RetryingHttpClient` with own implementation of `DynamicEndpointGroup` - the group periodically reads endpoints from an external source. The client retries on `UnprocessedRequestException` and this works nice but there are cases when the external source can return 0 endpoints for a short period of time (~ 10 to 30 seconds). In this case `UnprocessedRequestException` is thrown from `RoundRobinStrategy` but, obviously, there are no retries because it’s too early for retrying client to kick in. I really don’t want to have own retries on top of Armeria’s retries and think about adding a dummy artificial endpoint if there are 0 endpoints returned from the external source - so I can keep trying this “unreachable” endpoint until “good” endpoints arrive. Does this sound like a reasonable approach or maybe there are some better options?

**Comment by trustin** [comment]
Although not ideal, a workaround at the moment could be make an `EndpointGroup` return `127.0.0.1:1` when there are no healthy endpoints.

**Comment by trustin** [comment]
I'd like to target this issue for 1.0 again given its impact.

**Comment by trustin** [comment]
There are two things to fix for this issue:

1. When selecting an `Endpoint` from an `EndpointGroup`, we need to wait up to certain amount of time (connect timeout) before raising an `EmptyEndpointGroupException`.
   - We need to add a variant of `EndpointGroup.select()` that requires a timeout value and returns a `CompletableFuture<Endpoint>`. The new method could be used when a) initializing a new context and b) `RetryingClient` chooses a new endpoint.
2. Currently, on an `EmptyEndpointGroupException`, a request will always fail with a response whose failure cause is a `UnprocessedRequestException`, regardless of whether `RetryingClient` is present in a decorator chain or not. This behavior needs to change so that the successful re-attempts made by `RetryingClient` are passed to the caller.

Not sure this will be as easy as I described above (devils are always in details :scream:). Any better ideas or traps I didn't realize yet?

**Comment by minwoox** [comment]
Sounds good to me. 😄

**Comment by trustin** [comment]
Another idea - `HealthCheckedEndpointGroup` could return all endpoints if all endpoints are unhealthy :thinking:

**Comment by adriancole** [comment]
forgive the drive by but I guess the state of throwing exception is more a
"fail fast" thing which could be configured and if not then we can consider
how to handle temporary absence of all endpoints.

I dont recall the implementation here but iirc in finagle when fail fast is
off.. the down endpoints, maybe all, would be individual countdown buckets
..

https://github.com/twitter/finagle/blob/76f791937fb0e4ec8ec8cdea48ae001f0591071a/finagle-core/src/main/scala/com/twitter/finagle/liveness/FailureAccrualPolicy.scala

**Comment by trustin** [comment]
Thanks for a feed back, @adriancole. That's a good idea that's worth a separate issue - #2728.

**Comment by trustin** [comment]
> We need to add a variant of `EndpointGroup.select()` that requires a timeout value and returns a `CompletableFuture<Endpoint>`. The new method could be used when a) initializing a new context and b) `RetryingClient` chooses a new endpoint.

We currently require an `Endpoint` to choose the right `EventLoop`. Therefore, no `EventLoop` is chosen when we call `EndpointGroup.select()`. Which `EventLoop` or `Executor` should we use to get notified of the result of `select()`, then? :thinking:

**Comment by trustin** [comment]
> Which `EventLoop` or `Executor` should we use to get notified of the result of `select()`, then? :thinking: 

Maybe one of the `EventLoop`s of the current `ClientFactory`.

**Comment by trustin** [comment]
> Currently, on an `EmptyEndpointGroupException`, a request will always fail with a response whose failure cause is a `UnprocessedRequestException`, regardless of whether `RetryingClient` is present in a decorator chain or not. This behavior needs to change so that the successful re-attempts made by `RetryingClient` are passed to the caller.

This is done in #2736.
