### ISSUE TITLE
Add RequestLog.setName or similar

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1931]
In https://github.com/openzipkin/zipkin/pull/2709 I found it's very tedious to set a name to the current request in a client, since it requires concepts like `RpcRequest` and `originalRequest`. Having a simple way to set the name of the current request might be nice.

**Comment by anuraaga** [comment]
Somewhat related is the issue I ran into when adding `armeria-grpc`, that requiring a `Class` to initialize `RpcRequest` made logging the request difficult.

**Comment by anuraaga** [comment]
https://github.com/line/armeria/blob/master/brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientAdapter.java#L124 might also be related - logging utilities like this adapter probably shouldn't have to know what an `RpcRequest` is.

**Comment by adriancole** [comment]
For the discussion part, here are a few notes:

* users should be able to employ any part of the http request in order to derive tags, so if there is an rpc method attached to it.. fair game.
  * for example, spring does this to add the controller name as tags.
* I don't know if "log" is best place to label an http request, though it might be a mental glitch on my side. Maybe there are some armeria idioms my fingers aren't practiced at, yet. It seems more common to name the request itself. I would like to understand why that would be a problem as it isn't obvious to me.

PS the adapter isn't public so any methods there can be changed :)

**Comment by trustin** [comment]
A user can now set the current request's name via: `ctx.logBuilder().name("do-something")`. It can be set only once.

**Comment by adriancole** [comment]
ok thanks!
