### ISSUE TITLE
Consider a blacklist approach for RequestContextCurrentTraceContext

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1964]
An armeria app uses a tracing object that coexists with activity that is not request originated. Threads like these will result in the following message to be logged: 

```
                logger.warn("Attempted to propagate trace context, but no request context available. " +
                            "Did you forget to use RequestContext.contextAwareExecutor() or " +
                            "RequestContext.makeContextAware()?", new NoRequestContextException());
```

The advice is totally invalid in these cases as for example a scheduled thread or reporting loop has no relevance (afaik).

One way out is to allow configuration of a pattern of threads that should be ignored as opposed to spawning this message. This will allow options besides wild hacks or worse killing the log message.

Ex this is how sleuth handles one of the places that are relatively hard to shut-up :)
https://github.com/spring-cloud/spring-cloud-sleuth/blob/558900155adb1ae4a732cf450c216e2ff04a3f90/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersHook.java#L126

Another option is to introduce some sort of thread local which you can set to say "ignore". For example, I could set that in a thread factory in order to quiet the root thing I'm trying to do which is in some ways better than scary comments which may end up lying.

thoughts?

**Comment by adriancole** [comment]
For those requests who aren't request originated, I think they will need a fallback implementation based on normal thread local, and we'd have to consider what happens when they eventually create a client call..

**Comment by anuraaga** [comment]
Yeah I've generally ignored the message knowing it's about spans like 'SET blah' to MySQL which I wish didn't exist in the first place :P

But it's true that there are probably background operation use cases that should have the fallback propagation. I think what we've found is depending on where a trace is started (or span? or some other unit) we want to be able to set a custom context propagation system. It might not even be started - I can't think of a use case, but I guess it's possible there is a trace started by something on top of Armeria, but once it hits `BraveService`, we want to make sure context continues propagation using `RequestContext` instead of a threadlocal to allow for asynchronous operations. So being able to switch propagation methods at points in the trace. Seems complicated, but something we should think about for Brave?

**Comment by adriancole** [comment]
we could discuss in brave, just this is the only place we have such a
request context stealing so figured we would be in a better place to
discuss impact here.

another option could be to make a dummy request context as a seed value. my
wonder is if we had such we could simplify transitions to client contexts
later?

**Comment by anuraaga** [comment]
Yeah think we can discuss here, just wondering if it makes sense to add the switching mechanism in Brave. Allowing threads to opt-out of the warning handles many use cases, but still stuck for my database threadpool since it's used both during request handling and also in the background with things like `SET charset`. Being able to specify the trace context propagation method when starting a trace, instead of globally, would help with that.

**Comment by adriancole** [comment]
I agree it is worthwhile thinking through, if nothing else for brave 6. There have been cases especially around propagation policy (like which headers.. which is different than in-process) that need some rethought eventually. However, at the moment, trying to add a hook to the span about how you will look the same span up ends up contortionist I think (as currently any hints we store are inside the data in the thread local which we are currently discussing :P). That said each instrumentation could choose to do things differently, but we sortof already do because we never use thread locals in our code except crazy circumstances. regardless, feel free to raise a discussion on brave. tx!
