### ISSUE TITLE
Move to another CI?

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2006]
Recently, we have encountered an unexpected build fail issue(https://github.com/line/centraldogma/pull/426). 
And Travis CI is slower than other CI. 
* Appveyor took [`24 min 46 sec`]( https://ci.appveyor.com/project/line/armeria/builds/26845579)
* Travis took [`30 min 58 sec`](https://travis-ci.com/line/armeria/builds/123994667)

Travis CI is `25%` slower than Appveyor with the same PR.
 
Related work: I saw [an issue](https://github.com/typelevel/cats/pull/2823) which considers moving another CI([Semaphore CI](https://semaphoreci.com/)) to reduce build time.

**Comment by FultonBrowne** [comment]
You could use the built in GitHub actions, I use that for all my projects and it works well.

**Comment by anuraaga** [comment]
@FultonBrowne Thanks for the suggestion! I've taken a look at GitHub actions and held off on it for now since it doesn't seem to support build caching yet which should come in a month or two.

https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974/highlight/true#M630

I think we could use some separate storage with manual operations, but probably better for us to wait for that to be implemented in actions.

**Comment by trustin** [comment]
On the other hand, AppVeyor introduced BYOC jobs which allows us to use our servers for running the builds: https://www.appveyor.com/blog/2019/10/01/self-hosted-jobs-on-your-computer-or-in-cloud-vms/

**Comment by ikhoon** [comment]
Now we are using AppVeyor BYOC https://github.com/line/armeria/pull/2157
Special thanks to @trustin 🙇‍♂️🙏

**Comment by trustin** [comment]
It seems like we are still capped at 5 concurrent self-hosted Linux jobs and 2 concurrent AppVeyor-hosted Windows jobs. Let me contact to AppVeyor support to increase the cap for the self-hosted Linux jobs.

I don't expect them to cost us as much as they require for the AppVeyor-hosted jobs because most computation resources are provided by ourselves in self-hosted jobs. If it turns out to be still too much for us, we may have to switch to an alternative solution again.
