### ISSUE TITLE
`NullPointerException` in `ArmeriaGrpcServerInteropTest`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2008]
Found this from CI:

```
com.linecorp.armeria.server.grpc.interop.ArmeriaGrpcServerInteropTest > deadlineExceeded FAILED
    java.lang.NullPointerException
```

No stack trace unfortunately.

**Comment by trustin** [comment]
Reproduced locally with the following stack trace:

```
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.base/java.util.regex.Pattern.matches(Pattern.java:1174)
	at io.grpc.testing.integration.AbstractInteropTest.deadlineExceeded(AbstractInteropTest.java:1108)
```

**Comment by trustin** [comment]
It seems like the upstream client expects the server to respond with `CANCELLED` rather than `DEADLINE_EXCEEDED`: https://github.com/grpc/grpc-java/blob/39dc883b342f4ffab175195bb0a2e809f8bcd164/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L654-L667

`deadlineExceeded()` does not fail anymore if I change `GrpcService` to close the stream with `CANCELLED` instead of `DEADLINE_EXCEEDED` here: https://github.com/line/armeria/blob/armeria-0.91.0/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java#L182

However, after changing that, I see an intermittent failure at `deaelineExceededServerStreaming()`:

```
java.lang.AssertionError: 
Expected :DEADLINE_EXCEEDED
Actual   :CANCELLED
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.grpc.testing.integration.AbstractInteropTest.deadlineExceededServerStreaming(AbstractInteropTest.java:1148)
```

@anuraaga Any suggestions about the right way to fix this?

**Comment by anuraaga** [comment]
I think the failure when changing to `CANCELLED` is because we haven't added full support for `CallOptions` yet including `withDeadline`. Now that our gRPC support has gone from best-effort to mostly-full support, I guess it's a good time to implement it.

I looked into it, and the first is adding something like `ClientRequestContext.setResponseTimeoutHandler`. However, when thinking about this, I found that the default behavior is less customizable than the server side since it operatores on a private implementation detail, `DecodedHttpResponse`.

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java#L206

Instead of taking a `Runnable` like `ServiceRequestContext`, should we accept `Supplier<Throwable>` instead? Or any other ideas how to intercept response timeout on the client?

**Comment by trustin** [comment]
What do you think about adding `StreamMessage.abort(Throwable cause)`?

**Comment by anuraaga** [comment]
I'm not sure I understand - would the callback be passed the `DecodedHttpResponse`, though the signature would be `StreamMessage`? I think that could work.

**Comment by trustin** [comment]
I thought something like this:

```java
ctx.setResponseTimeoutHandler(() -> ((HttpRequest) ctx.request()).abort(someException));
```

**Comment by anuraaga** [comment]
Ah I see, the exception would replace the normal `AbortedStreamException`. That sounds good
