### ISSUE TITLE
Streamline HTTP header/trailer validation and conversion

### ISSUE THREAD

**Issue by trustin** [line/armeria#2096]
Currently, user provided HTTP headers and trailers are consumed by `HttpRequestSubscriber` and `HttpResponseSubscriber`. The following is the basic header/trailer validation and conversion process:

1. `Http*Subscriber` merges the `Request/ResponseHeaders` and `ctx.additional*Headers()` while excluding some prohibited headers.
2. `Http*Subscriber` passs the merged headers to `HttpObjectEncoder`.
3. `HttpObjectEncoder` converts the merged headers while excluding some more prohibited headers, using `ArmeriaHttpUtil`.

(Pretty much same for trailers)

Instead, we could streamline and optimize this process like the following:

1. `Http*Subscriber` passes `Request/ResponseHeaders` and `ctx.additional*Headers()`, without any validation or exclusion.
2. `HttpObjectEncoder` converts the given headers while excluding prohibited headers and merging `Request/ResponseHeaders` and `ctx.additional*Headers()`.

This way, we could reduce the number of unnecessary instantiation of immutable headers and their builders.

**Comment by jyblue** [comment]
Hello, I will challenge this issue :smile:

**Comment by jyblue** [comment]
I found a question while working on this :thinking: 

When we add additional response trailers to headers in `HttpResponseSubscriber`, we removes some prohibited headers(SCHEME, STATUS, METHOD, PATH) [here](https://github.com/line/armeria/blob/e21448a95b963cc0e6f349710f7ec1cf572b87af/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L203) and [here](https://github.com/line/armeria/blob/e21448a95b963cc0e6f349710f7ec1cf572b87af/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L237) via `fillAdditionalTrailers()` method.
But we don't remove here,
https://github.com/line/armeria/blob/e21448a95b963cc0e6f349710f7ec1cf572b87af/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L244
**Because, it is allowed to add the prohibited headers when this case happens?**

If this additional trailers are passed to `Http2ObjectEncoder`, it seems that the prohibited headers wouldn't be removed. In case of being passed to `Http1ObjectEncoder`, the prohibited headers would be removed by some duplicated excluding process.

**Comment by minwoox** [comment]
> Because, it is allowed to add the prohibited headers when this case happens?

No. I think it's a bug. 😅 All trailers should be treated in the same way. Please fix it as well. 😄
