### ISSUE TITLE
Content preview and compressed stream

### ISSUE THREAD

**Issue by trustin** [line/armeria#2189]
When sending or receiving a compressed stream, `RequestLog.contentPreview()` will preview the compressed content, which is not very human friendly.

It would be nice if we can push the uncompressed content preview to `RequestLog`, with low overhead. Currently, a user can write a content previewer that performs decompression, but it means the content will be decompressed twice, once for previewing and once for actual content decoding.

**Comment by snaiper80** [comment]
I also need this exactly. Currently, I implemented a simple content previewer that is naive approach using `ContentPreviewerFactory` to decompress the gzipped body stream. But this codes have been running in debug mode only due to performance problem as you're already said.

**Comment by trustin** [comment]
@anuraaga Any thoughts on this? I can't think of a way to handle this nicely..

**Comment by anuraaga** [comment]
@trustin I guess instead of being called in-band by `RequestLog`, the functionality can be moved to a decorator? Then a user gets to decide too whether they want to preview the encoded or decoded content. I think the main APIs are already there, `RequestContext.logBuilder().requestContentPreview(String)` so just need to move the logic to a decorator. It's similar to the decorator linked in #1997 except that used `aggregate` for ease of implementation, while it's not that much worse to use a normal subscription.

**Comment by anuraaga** [comment]
@trustin Probably good to target this for 1.0.0

**Comment by trustin** [comment]
Yeah, I wonder how it will impact our current service binding builder API. It would result in a surprise if a user specifies previewers there and forgets to add a previewing decorator. Any idea for preventing this? Just checking with `as()` ?

**Comment by minwoox** [comment]
>  I guess instead of being called in-band by RequestLog, the functionality can be moved to a decorator?

That's a good idea. Let me work on this. I think we can add `ContentPreviewingService` and `ContentPreviewingClient` with their builders. Inside the decorator, we can use `FilteredStreamMessage` to subscribe once.

**Comment by anuraaga** [comment]
@trustin Sorry for not replying to your question. My idea was just to remove the current service binding content preview flags since the decorator itself could have all the configuration.

**Comment by minwoox** [comment]
Yes, we can completely move the logic to the decorators. 😉
