### ISSUE TITLE
When do we need to call ctx.push()?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2232]
Found out that we are pushing context while notifying log listeners:
```java
try (SafeCloseable ignored = log.context().push()) {
    listener.onRequestLog(log);
}
```
The listener can get the `ctx` from the method parameter `log` using `log.context()`.
Should we push the `ctx` in such a case in which the thread is able to get the `ctx` from the parameter?

**Comment by minwoox** [comment]
One thing I noticed recently was that some of our clients are using `ctx.onEnter()` and there is some heavy initialization logic called multiple times. However, after #2227 is merged, it shouldn't be a problem though.

**Comment by trustin** [comment]
#2375 will remove `onEnter()` and `onExit()` by the way.

**Comment by trustin** [comment]
I agree that we need to avoid pushing a context unnecessarily, and thus we should not push a context when a callback is given a context as a parameter. Thoughts? /cc @ikhoon @imasahiro @kojilin @anuraaga

**Comment by anuraaga** [comment]
I agree with the general idea of not pushing when `ctx` is referencable by the user. There is one caveat in that sometimes features require the context to actually be in a thread local to work - if we didn't push context in the brave decorators tracing wouldn't work properly. So sometimes it's not only about finding a `ctx` variable in scope or not. This will be a very low minority of the cases though.

**Comment by minwoox** [comment]
Oops, I forgot to leave a comment for this.
I think it's okay to push the context when we call `onRequestLog()`.
(Sorry I've changed my mind. 🙏)

The reason I filed this issue is that 1) we had a bug which was raising an exception when calling `ctx.makeContextAware` with a `ClientRequestContext` in the thread-local 2) I saw some really heavy initialization logic in `onEnter()`.
But now, we fixed the bug and we will remove the `onEnter` and move to using sort of `Storage` which users wouldn't not put some heavy initial logic when they just call `doAttach()` (I guess 😅).

Also, as @anuraaga explained, a user could add a decorator which sends a request to another backend when `RequestLogAvailalibility.COMPLETE` is fulfilled. It will need the ctx in the thread-local.

So I think we need to push the ctx when calling `onRequestLog()`.
Sorry for making a noise again. 🙏

**Comment by trustin** [comment]
Isn't pushing a context still some amount of overhead? The decorators like `Brave{Client,Service}` could push the context manually? I'm not strong on either options but I'm curious if it's possible to remove `ctx.push()` for lots of things - `Client.execute()`, `Service.serve()` and `RequestLogListener`.

**Comment by anuraaga** [comment]
@trustin Right, sorry what I meant is that the brave decorators would still need to push the context while we don't need to push it in many other cases we do now. Just that the decision to push is not as trivial as "is there a variable named ctx in scope", though I wish it was ;)

**Comment by minwoox** [comment]
> Isn't pushing a context still some amount of overhead?

I think it's not that much, but I think I should do the benchmark for that.

> Client.execute(), Service.serve()

I think we need the `ctx` in the thread-local for Retrofit client, Thrift, gRPC client and services.
So I think it's a little bit awkward not to push the context only for the `WebClient` and `HttpService`. 🤔

**Comment by anuraaga** [comment]
To add a bit more context (yes I said it feel free to bring out the 🗡 ;)

- I am most concerned about the performance of automatically mounting the context in a `Subscriber`. I don't think `onNext` should be treated specially within a `Subscriber` since it's all part of the same interface, but in that case if we automatically mount in subscirbers,  we mount in `onNext` which can be fairly significant. I don't mind mounting once per request, it's quite small compared to once per `onNext`, which I mentioned in #2363 as something to think about, which probably brought back the conversation. However I'm pretty sure we've already settled on not mounting automatically in subscribers (actually it looks like passing a context aware executor is way better), if so it's mainly about methods like `execute` and `serve`

- I personally don't mind having discrepancy between Armeria API vs integration APIs like gRPC, retrofit. I've always considered the thread-local as the only means to interface with non-Armeria APIs (brave also falls into this category), and it's not a means to interface with Armeria APIs (which have ctx in their method signatures so no need to mount). This distinction seems pretty natural to me.

**Comment by minwoox** [comment]
> However I'm pretty sure we've already settled on not mounting automatically in subscribers

I thought we've already decided not to push the ctx. 😆 

> I personally don't mind having discrepancy between Armeria API vs integration APIs like gRPC,

Yes, I agree with it. 😅 I should've given another example for that.
I think there's a chance that an `HttpService` which triggers to send a Thrift or gRPC requests to the other backend. The client has to know about `root` so that it can do (for example) tracing. 😄
Also because the `ClientRequestContext` knows about the `root` which invoked that client call, we can validating when pushing and don't have to copy all the attributes, and so on.

In order for the `ClientRequestContext` to have the root, I don't have any other solution except the way we are doing right now. 🤔

**Comment by anuraaga** [comment]
Thanks for the example! Indeed, we rely on the thread-local to manage the service root context - this does indicate that the server does need to always mount the context once. We could or could not mount the client context for symmetry, even though we don't have such a use case for it. I would lean towards not, since we already decided not to have `ClientRequestContext` as a root since there doesn't seem to be a reason for it, so we can be explicit about it in our code. But I don't feel strongly at all about that. 

I realized, for this discussion, maybe it's good to go ahead and make a bullet list of all the cases we mount context currently so we can give them a yes/no.

**Comment by minwoox** [comment]
Oops, I realized that the RxJava hook uses that too. https://github.com/line/armeria/blob/master/rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextAssembly.java#L238

So if a user uses RxJava APIs in a client decorator, we should still push the context into the thread-local.

So I guess, we have only one left. `RequestLogListener`
Because we are revamping RequestLog APIs so the stages of `RequestLogAvailability` will be reduced (which means that the overhead wouldn't be much), I think it's okay to push the context.
But I'm not so strong on this. 😉

**Comment by minwoox** [comment]
`onEnter` and `onExit` are now gone.
We don't have to worry about `RequestLogListener` because we use `CompletableFuture` and callbacks.
For `Client.execute()` and `Service.serve()`, we need to push because of RxJAva hooks and validation logic.
So I think it's okay to close this issue. 😄
