### ISSUE TITLE
Request time does not take into account connection creation

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2272]
Reported in https://line-armeria.slack.com/archives/C1NGPBUH2/p1574122806097100

I believe this is a regression after moving `Endpoint` selection to the begging of the request. We call `startRequest` only when about to send the request, but not anymore. This is affecting spans, but I think it also affects our `totalDuration` metric equally.

**Comment by anuraaga** [comment]
To some extent, where we start and stop the request timing is up to us - but especially since we have the wire annotations now, it seems fine to me to have the total span duration match the invocation of the stub method (I guess basically `invoke() -> completionFuture()`). A good enough approximation I'm seeing is to just set the start time when a `ClientRequestContext` is constructed.

**Comment by trustin** [comment]
+1 for setting the start time when the context is constructed

**Comment by anuraaga** [comment]
It might be great timing to reconsider the `RequestLog` API - I find the `RequestLogAvailability` to be so fine-grained that it's fairly hard to understand, and it makes working with logs (e.g., adding a new logged metric) in Armeria very tedious. I wonder how many people need any availability other than `Complete` - I think log usually ends up being processed / stored into something after a request has finished in most (all?) use cases. With the brave sampler integration, I think we found that the availability didn't really matter and was making the code more complicated when it just needed to either have the information if already available or skip it. Any thoughts? Should we open another issue?

**Comment by anuraaga** [comment]
So - any thoughts on the change to the logging API regards to availability setting? :) @trustin @minwoox @ikhoon

**Comment by trustin** [comment]
Sorry, missed your comment. How about assuming `COMPLETE` when a user specified no availabilities? That would be less confusing I guess.

**Comment by anuraaga** [comment]
@trustin I find it more difficult to actually log things, since it involves figuring out or making a new availability (which are technically not infinite with the current implementation using a bitset). I think your suggestion is referring to consuming logs, but I'm more concerned about adding logs. 

For this issue, right now, we have `REQUEST_START` which contains the start time, channel, and other bits, so if we want to change the timing of when we log `requestStartTimeMillis`, it's very tedious due to the coupling. It was similar when adding the `firstBytesTransferred` metrics. I'm not sure the value add of these availabilities is enough to warrant it being so difficult to add logging.

**Comment by trustin** [comment]
I agree that having too fine-grained availability is bad, but I'm not sure about 'how fine-grained' we need go.  Just having `COMPLETE` doesn't sound like a good idea, either, because some will want to reduce the latency between the actual event and notification. Do you have some specific suggestions for simplification? I did a quick look and it seems to me that `SCHEME` maybe can be merged into `REQUEST_HEADERS`, but that's all?

**Comment by anuraaga** [comment]
Looking at the usage in the Armeria codebase, `COMPLETE` seems to be used the most. I do see a use case for `REQUEST_END` since there could be services that last a long time between getting a request and finishing, but really don't see much utility for e.g., splitting the notification for even headers / content, for example. We have some listeners that export to metrics but metrics are averaged anyways and don't benefit from such fine-grained notification.

That being said, I realized the opposite idea may make sense too - make availability extremely fine grained by having one for each piece of data that's recorded. Then, adding a new metric is just adding to an enum and saving to the field. Users could have immediate notifications for the data they're interested in, or keep things simple by just listening for completion (we store the listeners with an `EnumMap`). The bit arithmetic of the current availability goes away along with the coupling that currently can make tweaking things difficult. If that sounds ok, I think it'd help a lot.

**Comment by trustin** [comment]
Unless we're going to add more than 64 event types, that's basically hiding bit arithmetic into `EnumMap`. I think we will soon use int or long as an internal representation of listener's interest when we optimize things, i.e. bit arithmetic is inevitable, although we can simplify it.

I agree that having an enum value for each field and removing getter/setter flags will simplify our code a lot, without making too big breaking change, if we can let users add coarse grained listeners, such as for `REQUEST/RESPONSE_END` and `COMPLETE` availability.

Thoughts? @minwoox @ikhoon

**Comment by minwoox** [comment]
How about providing a new API like `onRequestLogComplete(...)` to `RequestContext` or `RequestLog`?

I really wanted to get rid of every `availability` when I saw this code from the user:
```java
ctx.log().addListener(log -> {
    // Log request and response content.
, RequestLogAvailability.REQUEST_CONTENT, RequestLogAvailability.RESPONSE_CONTENT);
```
Of course, this works as expected, but he could just use `RequestLogAvailability.COMPLETE` without much worrying about what kinna availability he had to use.

However, there should be others who want to reduce the latency between the actual event and notification. I used `RequestLogAvailability.REQUEST_HEADERS` in `RetryingClient` to decide to retry as soon as possible. I think `REQUEST_HEADERS` and `RESPONSE_HEADERS` are needed especially when streaming requests and responses.

Therefore, I think it's good if we provide a simple API for most of the users and fine-grained APIs for advanced users so that the APIs are separated and most of the users would not worry about `RequestLogAvailability` because they wouldn't use it.

For the `EnumMap`, if it simplifies our APIs, there's no reason to be against it.

**Comment by anuraaga** [comment]
I think we agree there's some simplification we can do. If it's ok, let me play around with this by switching to field-level availability with some coarse-grained callbacks, and see how things turn out.

**Comment by trustin** [comment]
OK. Thanks for looking into this, @anuraaga!

**Comment by trustin** [comment]
@anuraaga Are you working on this? I'm thinking of adding `RequestLog.name` to resolve https://github.com/line/armeria/issues/1931, so I might need simplification.

**Comment by anuraaga** [comment]
Hi sorry - I have a WIP let me finish it up around tomorrow

**Comment by trustin** [comment]
I have been thinking about simplification this week and thought perhaps we can reduce the granularity to:

- `REQUEST_IDENTIFIED`
  - Basically when we can build a correct meter ID for metric collection, e.g. request name (or RPC method name) has been determined.
- `REQUEST_END`
- `RESPONSE_END`
- `COMPLETE`

.. because there has not been any use case reported so far.

**Comment by trustin** [comment]
> Hi sorry - I have a WIP let me finish it up around tomorrow

No worries. Please take your time. I will look into other issues. :wink:

**Comment by trustin** [comment]
Let me try to take a look into this soon.
