### ISSUE TITLE
Add image for slack invitation link 💌

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2274]
I have seen some slack invitation images for the invitation link. 
The invitation image would be better than plain text to new Armeria user to find slack link. 😉

For example:
![](https://user-images.githubusercontent.com/609349/63558739-f60a7e00-c502-11e9-8434-c8a95b03ce62.png)

**Comment by ikhoon** [comment]
@syleeeee Can we get the invitation image from the LINE’s internal designer👨‍🎨?  🙇

**Comment by syleeeee** [comment]
Sure! I'll talk to her and get back to you.

**Comment by syleeeee** [comment]
@ikhoon 
Thinking of the suitable image size, I realized that we haven't included any icons in the README. 
It would be awkward if people's eyes are taken away to the image button, not the project itself when the button image is in the middle. 

As an alternative, wouldn't the badges be simple and familiar instead of the invitation button? Also, we're already using the badges in [the main page](https://line.github.io/armeria/).
What do you think? 👀

**Comment by ikhoon** [comment]
I agree that the image button is a little strong for our `READMD.md`. Badges are simple and used among lots of open source projects in GitHub.

Furthermore, if we use badges, users can easily check the Maven release version and build status. 👍 

Let's use badges!

**Comment by ikhoon** [comment]
Badges are added to README.md in https://github.com/line/armeria/pull/2682/files#diff-04c6e90faac2675aa89e2176d2eec7d8 😀
