### ISSUE TITLE
Automatic propagation of RequestContext

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2347]
One of the most complaints from the users is that they are struggling to propagate a `RequestContext`. Check out this snippet:
```java
@Override
public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) throws Exception {
    backend1.execute(req).aggregate().handle((aggregatedRes, cause) -> {
        // ctx is not in the thread-local. You should use ctx.makeContextAware() or contextAwareExecutor
        backend2.execute(req)...
    });
    ...             
    return res;
}
```

If we return a `RequestContextAwareCompletebleFuture` from `aggregate()` call, most of the situations are solved because `RequestContextAwareCompletebleFuture` keeps spwaning the future itself when adding callbacks.

Of course, we cannot propagate the `ReqeustContext` all of the cases. For example, if a user creates a new `CompletableFuture` instance and completes it with a value, the `RequestContextAwareCompletebleFuture` will stop spawning.
So he/she has to understand how the propagation works to use Armeria properly.

However, I think Automatic propagation will still reduce the burden of users who are not familiar with the asynchronous server and can lower the entry point.

**Comment by minwoox** [comment]
@anuraaga I wanted to listen to your opinion before I go ahead because I feel you are reluctant Armeria to have this feature. 😄

**Comment by anuraaga** [comment]
> However, I think Automatic propagation will still reduce the burden of users who are not familiar with the asynchronous server and can lower the entry point.

I think you know my opinion ;) 

If relying on context and writing an asynchronous server, knowing how context works is a requirement - I find bandaids to be worse since the context bug will inevitably appear, but later in the lifecycle of the codebase and has an even higher chance of affecting production vs development servers. Being confused in the beginning is better than later IMO.

Also, IMO writing asynchronous code effectively basically requires a framework on top of Armeria for a reasonable sized app. I personally know Dagger makes it trivial to solve the context problem completely where it would be harder for a user to make a mistake than do the right thing. I have heard of rxjava users forgetting to subscribe correctly - perhaps enforcing use of something like `ArmeriaFlux` that automatically subscribes would be harder to forget. I was a little interested in seeing what approaches could help with RxJava but currently have no plans of using it so not sure if I could come up with anything but it seems like a better layer to deal with asynchronous issues than our custom `CompletableFuture` implementation.

Also just for reference, golang and gRPC both have context and take the approach of no automation at all (note, the Armeria context is a combination of gRPC concepts of `Call` and `Context`, only `Call` is automatic in gRPC). Creating and propagating context is all up to the user. This creates some tedium, and I do think automatically creating context like Armeria does is better, but I do like how it forces users to understand context before using it.

These are my opinions and some reference point, I wouldn't say no if everyone still felt automatic propagation makes sense :)

**Comment by minwoox** [comment]
Thanks for your opinion. I do agree with most of the problems you pointed out. 😄
Let me figure it out how we handle (or don't handle) this whole context propagation things so that users can use Armeria in a better way. 😃

**Comment by trustin** [comment]
I prefer automatic context propagation. It will be bad if there's an inevitable pitfall that lets a user get a completely wrong context, but I guess we have fair amount of protection for that in @minwoox's recent work. :clap: 

As @anuraaga pointed out, an unpropagated context can be a problem with automatic propagation because a user may have hard time finding out where the propagation stopped, but I think the convenience outweighs this problem and the tedium of explicit propagation.

Learning how a context propagates is an important matter when building a complex asynchronous application, and I agree that an automatic propagation may mislead some users to believe things will just work magically and eventually shoot themselves on their feet. However, wouldn't it still happen anyway even with explicit propagation as long as they cargo-cult `makeContextAware()` and not test enough? :sweat_smile:

**Comment by trustin** [comment]
@imasahiro @kojilin @taicki @julnamoo @hktechno @renaudb What do you think? Which would you prefer, automatic or manual context propagation?

**Comment by trustin** [comment]
@imasahiro @kojilin @taicki @julnamoo @techno @renaudb What do you think? Which would you prefer, automatic or manual context propagation?

**Comment by trustin** [comment]
and @tobias- as well.

**Comment by anuraaga** [comment]
> the tedium of explicit propagation.

My point doesn't seem to have gone across - no one should explicitly propagate context. But for complex async apps, they should use something's like Kotlin, RxJava, or Dagger which have good tools for automatic propagation of context even for non-Armeria code. So understanding context is mostly just to the extent if using it properly with these tools. I think it's better for the Armeria team to focus on teaching these practices rather than creating a bandaid that pops off as soon as a user uses MySQL or Redis (most do, right? ;) )

**Comment by trustin** [comment]
I see where you're coming from now :smile: 

But does automatic context propagation interfere with those technologies? It's still useful for simpler applications, so I think it'll be nice to have something easy to use in our sleeves for those who starts to play with Armeria.

**Comment by renaudb** [comment]
I don't feel strongly one way or another. We've been burned by it in the past when using static `CompletableFuture` methods such as `allOf` or `anyOf` which won't be automated with this proposal, so we're already more careful about it.

**Comment by julnamoo** [comment]
> Learning how a context propagates is an important matter when building a complex asynchronous application, and I agree that an automatic propagation may mislead some users to believe things will just work magically and eventually shoot themselves on their feet.

Thinking it is the point is understanding the context propagating rather than introducing the automatic propagation ☔️

**Comment by anuraaga** [comment]
> But does automatic context propagation interfere with those technologies? It's still useful for simpler applications, so I think it'll be nice to have something easy to use in our sleeves for those who starts to play with Armeria.

I worry what happens when the user starts to play, then adds in their DB call and get hurt. I'm also worried about a codebase that only uses context-awareness for non-Armeria, and the reduced reasonability of the code.

I found in #2363 that even for a very simple server, automatic propagation wouldn't work mainly due to @renaudb's good point of the static future methods not being intercepted.

Also, while probably not direct interference, I think automatic propagation would have an unecessary performance cost. I always recommend asynchronous logic to use `ServiceRequestContext.contextAwareExecutor` for all callbacks since not only does it keep context mounted but runs all logic on the same thread which tends to be better for performance / concurrency. And for non-Armeria callbacks, But if we automatically mounted `ClientRequestContext` in a client callback, then for these users they will end up remounting `ServiceRequestContext` on top of that, which is pretty significant performance. Even if we decided to mount `ClientRequestContext.root` in a client callback (not sure if this makes semantic sense when scoped to just a client), there'd still be the thread-local check + no-op.

So I think we'd need a `ClientOption` to control the automatic propagation if going with it, ideally opt-in. But I'm not sure I would ever recommend using the option...

**Comment by minwoox** [comment]
Due to the limit that we cannot do it automatically in all cases, it seems like the cons heavily outweigh the pros. So let me close this and thanks all for the valuable opinions!

For the consistent APIs, let me revert the RpcResponse back to `DefaultRpcResponse`.

**Comment by trustin** [comment]
Thanks a lot for valuable feed back, folks. :bowing_man:

**Comment by tobias-** [comment]
Sorry I didn't chip in before. I took an extended vacation during christmas/new years. For the record, my vote is with @anuraaga in that I prefer explicit propagation. The only problem with that is afaik grpc server methods, because they have a fixed signature, which afaik does not include access to any armeria-specific context. Since I write in Kotlin, I use coroutines(fibres?) extensively, but I've yet to encounter any case where I need access to that context beyond the authentication methods and access logger.

I come from the jaxrs-world, so I'm used to the magical `@Context/@Inject` `Proxy`s, but haven't seen or used anything that would help propagate that context to other threads, thus more or less forcing everything related to the actual http request to be in the top-most layer or in special servlet filter-like classes that are more or less forced to be single-threaded.

@minwoox  Thanks for the `ServiceRequestContext.contextAwareExecutor` reference. Although magical and I don't see a use for it yet, it will fit nicely with coroutines.

**Comment by minwoox** [comment]
> @minwoox Thanks for the ServiceRequestContext.contextAwareExecutor reference. 

It's not me. Thanks to @anuraaga. 😆
