### ISSUE TITLE
Provide RedirectingClient

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2489]
A user has to do it by himself/herself to handle a redirect response:
```java
WebClient client = ...
AggregatedHttpResponse res = client.get("/redirect").aggregate().join();
String location = res.headers().get(LOCATION);
if (location != null) {
    AggregatedHttpResponse redirected = client.get(location).aggregate().join();
} else {
    ....
}
```
It's a little verbose so it will be nice if we provide `RedirectingClient`.

**Comment by minwoox** [comment]
@trustin suggested that we can just do this by providing `RetryStrategy.builder()` #1634, because the logic is nearly the same and redirect is sort of retry. 😄

**Comment by JunoJunho** [comment]
I think this methodology can solve only one redirection.

How about using while loop ?

like

```
while (location != null) {
    AggregatedHttpResponse redirected = client.get(location).aggregate().join();
    location = redirected.headers().get(LOCATION);
}
```
?

**Comment by anuraaga** [comment]
I think many clients have a follow_redirects client option. While admittedly we found the content previewer to be more appropriate as a decorator, since this is literally the HTTP spec, maybe an option is easier to reason about than decorator (could still be implemented as internal decorator if that's simpler). Retrying has a backoff, with our default being exponential - I'm not sure it's good to conflate redirect with a potentially exponential retry in the API.

**Comment by minwoox** [comment]
If we provide it using a client option, which is probably in the form of an internal decorator, couldn't the order of the decorators be decided when `LoggingClient` and `MetricCollectingClient` used?
Also, If `RetryintClient` is used, we have to duplicate the request in two places and the logic would be mostly duplicated, so isn't there any performance impact?

**Comment by minwoox** [comment]
> How about using while loop ?

@JunoJunho
We are looking for a way that a user doesn't have to do this and just use the `WebClient` like there's no redirection happened. 😆

**Comment by anuraaga** [comment]
> couldn't the order of the decorators be decided when LoggingClient and MetricCollectingClient used?

Not sure I understand this question but I'd generally expect a redirecting client to always be last

> so isn't there any performance impact?

This is true, but I don't know if it's worth avoiding it since in the case with only redirects, the API seems like it would get quite confusing. Redirects are part of the HTTP spec and don't need customization, but `RetryingClient` provides a lot. I guess we'd basically ignore all customization only for redirects but feels a bit random.

We could probably hide it from the user, if it is a client option, any retrying client in the chain can respect it and implement the redirect. And if there isn't one in the chain, client builder can add the decorator.

**Comment by minwoox** [comment]
> Not sure I understand this question but I'd generally expect a redirecting client to always be last

What I meant was that, is there any chance that a user sets the `MetricCollectingClient` or `LoggingClient` last so he/she doesn't want to care about redirecting. 😆

 > any retrying client in the chain can respect it and implement the redirect. And if there isn't one in the chain, client builder can add the decorator.

That sounds good.

**Comment by anuraaga** [comment]
Aren't those decorators independent of decoration order since they just register log listeners?

**Comment by minwoox** [comment]
If the call is
`client` -> `RedirectingClient` -> `LoggingClient` or (`MetricCollectingClient`)
then, the redirecting is logged as well.

If the order is different which is:
`client` -> `LoggingClient` or (`MetricCollectingClient`) -> `RedirectingClient`
the redirecting is not logged.

It's described here. http://line.github.io/armeria/client-retry.html#retryingclient-with-logging
🤔

**Comment by anuraaga** [comment]
Oops didn't realize they treat child logs differently 😅
