### ISSUE TITLE
Consider adding hooks back to `RequestContext`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2514]
This is a follow-up discussion of https://github.com/line/armeria/pull/2375

It seems pretty common for users to set/clear a thread-local variable based on the life cycle of `RequestContext, e.g.

```kotlin
serviceContext.onEnter { _ ->
    MDC.put(correlationIdKey, context.correlationId)
    MDC.put(requestIdKey, context.requestId)
}
serviceContext.onExit { _ ->
    MDC.remove(correlationIdKey)
    MDC.remove(requestIdKey)
}
```

This is doable via `RequestContextExportingAppender`, but in some cases like the above, callbacks can be much simpler and more efficient. (See the thread from @andrewoma at: https://line-armeria.slack.com/archives/C1NGPBUH2/p1582090225136400)

**Comment by trustin** [comment]
The problem with the old API (`onEnter()`) is that a user can add it only *after* the context is pushed, which means that the following code will never set `MDC` at all:

```java
Server server = Server
  .builder()
  .service("/", (ctx, req) -> {
    ctx.onEnter(unused -> MDC.put(..., ctx.id()));
    logger.info("MDC will not be set at all for this message.");
    return HttpResponse.of(200);
  })
  .build();
```

**Comment by trustin** [comment]
Therefore, @anuraaga suggested an alternative API similar to https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.Storage.html

We might want to provide something with better usability, though, like:

```java
Server server = Server
  .builder()
  .contextStorage(new ThreadLocalContextStorage() {
    // Invoked before invoking the decorator chain.
    @Override
    public void onEnter(ctx) { MDC.put(..., ctx.id(); }
    ...
  })
  ...

WebClient client = WebClient
  .builder(...)
  .contextStorage(...)https://github.com/contact
  ...
```

**Comment by anuraaga** [comment]
From what I understand, the example in the original issue is at least less efficient (why use a callback to sync one threadlocal to another when you don't have to) and not clearly simpler. Can you explain more concretely why the callback would be better? I don't think log MDC is a use case for a context storage API.

**Comment by trustin** [comment]
> the example in the original issue

Which one is it?

**Comment by anuraaga** [comment]
Sorry I was trying to translate "Original Post" like on Reddit and didn't do it right 😅 I meant top post of this issue.

**Comment by trustin** [comment]
I thought callbacks are more efficient than `RequestContextExportingAppender` in this specific example, because putting request ID is just a single `MDC.put()` call while while `RCEA` has to 1) re-export when availabilityStamp changes and 2) create a union map for each log message.

Maybe controversial, but some may think one way or the other way clearer.

**Comment by anuraaga** [comment]
Ah I guess that means exporting Armeria values like the request id without using `armeria-logback` at all. Without benchmarks, it's hard to say for sure but I would still suspect the exporter to be better - there is the same number of reads from a threadlocal, but the exporter doesn't need to remove attributes one-by-one. 

Anyways considering the original request was about logging context information, but we already support this, I don't see why adding hooks is a solution. If dealing with logback.xml is tedious, we could provide Flags.java or tweak the defaulted attributes to reduce the tediousness. But it sounds like a configuration issue rather than a semantic one, which would require a new API like onEnter.

**Comment by ikhoon** [comment]
```java
    // Invoked before invoking the decorator chain.
    @Override
    public void onEnter(ctx) { MDC.put(..., ctx.id(); }
```
I wonder invoking before the decorator chain is enough? `MDC.put(...)` will put `ctx` into current thread local storage. 

I guess the `MDC.put(...)` should be called again when `RequestContext` is propagated to other threads like RxJava execution scheduler.

**Comment by minwoox** [comment]
No matter is this the case or not, shouldn't we provide the method which is going to work as  `onEnter` did? 😆

**Comment by anuraaga** [comment]
Yeah I still think we should add the context storage customization option - it's quite different than just adding hooks back to RequestContext like this issue.

**Comment by andrewoma** [comment]
I feel like there needs to be some way to achieve what the hooks did. Perhaps the Appender approach is better for this particular use case of MDCs (however, it currently doesn't work in the same fashion and has a large amount of moving parts to take on). 

`ThreadLocals` are kind of necessary to integrate with various frameworks. Maybe there's a middle ground of downcasting if usage is to be discouraged.

**Comment by andrewoma** [comment]
I'd also add it's not so much about context storage, but if there's a legacy framework expecting something to exist of a `ThreadLocal`, I can't see any way of setting it up and tearing it down when a request context begins execution on a given thread

**Comment by anuraaga** [comment]
Yeah I brought exactly that up in the original discussion

https://github.com/line/armeria/pull/2375#issuecomment-571028023

Searching through many libraries that rely heavily on context, I couldn't find one that did not provide customization of the context without threadlocal syncing. One open source usage of the hooks I found was actually buggy because the hooks do not provide a clear lifecycle, and replacing with a context storage customization approach fixed it up. It reminds me of our brave support too, which took many versions to work out using the threadlocal syncing, and all the hacks we added could go away by removing the syncing completely.

Context storage customization can provide the lifecycle hook even for syncing things like a threadlocal if a library does come up which requires it. But we were thinking of doing that post-1.0 since we haven't found one yet.

I think we found specifically to logback which prompted this issue
- The exporter had a lot of bugs. These are mostly fixed.
- Working in logback.xml may be tedious. If so, we could probably provide a programattic approach for logback too that uses the exporter without adding these dangerous hooks

**Comment by andrewoma** [comment]
I think I largely agree with your assessment. I guess I was just getting extremely nervous (and still am to a certain extent) of hitting a blocker where I can't upgrade Armeria. The removal of `onEnter/onExit` means the `Appender` _has to work_, or I'm essentially blocked. @trustin has just reproduced and fixed that issue, so I'm hopefully unblocked and can continue on. But I completely understand you don't want to commit to an api you're not happy with for 1.0.

**Comment by anuraaga** [comment]
Thanks and sorry for the nervousness. Indeed, we definitely do not want to block any current code. Hopefully the bug fixes work things out.

**Comment by minwoox** [comment]
@anuraaga I'm working on providing a way to customize the context propagation.
One of our customers uses Armeria and another framework together, (which means `RequestContextExportingAppender` can't be used), and they use MDC, so I need this.

I was sort of thinking of two ways:
- Add a `Supplier`, which emits `Storage` to `ClientBuilder` and `ServerBuilder`.
- Use Java SPI to create the `Storage`.

The first one is for just in case, a user wants different storages for the `ClientRequestContext` and `ServiceRequestContext`. But I highly doubt that if there's such a case.
So I lean toward the second option. Do you have anything in mind before I get into this?

**Comment by anuraaga** [comment]
Nope SPI sounds good :)

Just wondering, what situation results in the appender not being usable? "One of our customers uses Armeria and another framework together, (which means RequestContextExportingAppender can't be used), "

**Comment by minwoox** [comment]
Stopped to upgrade. 🤣 I was actually trying to add fake `ServiceRequestContext` using `ServiceRequestContextBuilder` for the requests come through the framework, but it's huge so I gave up. 😆
