### ISSUE TITLE
Should `ServiceRequestContext` be nested?

### ISSUE THREAD

**Issue by trustin** [line/armeria#2524]
Related Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1582121306153900

Let's say there are two annotated services in a server where Service A handles Request A by returning an `HttpResult.from(someFuture)` and Service B handles Request B by completing `someFuture` with `someValue`.

When Service B completes `someFuture` with `someValue`, its thread-local context is for Service B, but Armeria will try to push the context for Service A when converting `someValue` into an `HttpResponse`, resulting in `IllegalStateException`, because `ServiceRequestContext` cannot be nested.

It seems to me that this kind scenario can happen for any situation that the completion of future for one service is done by another service.

Should we allow `ServiceRequestContext` be nested, or is it enough to fix this specific case by `pop()`ing the existing context given that this kind of scenario isn't that frequent?

**Comment by trustin** [comment]
The workaround for the user was to use `thenApplyAsync()` to detach the context: 
```java
HttpResult.from(someFuture.thenApplyAsync(Function.identity(),
                                          ctx.eventLoop()));
```

**Comment by anuraaga** [comment]
Hmm, I thought we've always prevented pushing `ServiceRequestContext` when there is already one mounted but maybe that started working at some point.

I found my original error message for the case

https://github.com/line/armeria/commit/9935d809aff1a39055d6df2076401303c5e92020#diff-4567e9c0de842b25af55d03fc493f88bL176

I vaguely remember adding this check because I found it relatively easy to end up tracing into the wrong location when saving futures, for example in an asynchronous cache, so it was important to have the error to indicate the need to move onto the `contextAwareEventLoop` for all handlers that work with cached futures (to not accidentally end up back on the cached context).

I think having service A context back may be correct in some cases and wrong in some cases - without a general way to know if it's ok or not, crashing loud and giving users the chance to be more explicit by making sure to use it's `contextAwareEventLoop` for context awareness seems safer.

**Comment by minwoox** [comment]
> crashing loud and giving users the chance to be more explicit by making sure to use it's contextAwareEventLoop for context awareness seems safer.

+1 for this.
I think a user has to understand the situation and specify the context manually.
If we just allow to push the context, when `RequestContextExportingAppender` is used, the log could have wrong context.

**Comment by trustin** [comment]
Agreed. Closing.
