### ISSUE TITLE
Adding circuitBreaker name on into CircuitBreakerMapping

### ISSUE THREAD

**Issue by JunoJunho** [line/armeria#2527]
Current `ofDefault` method in `CircuitBreakerMapping` uses `KeyedCircuitBreakerMapping.defaultMapping`, which is `CircuitBreaker.of` method with empty name, but in some case, there is a need to give circuitBreaker name on this.

How about adding override method for this?

**Comment by minwoox** [comment]
`KeyedCircuitBreakerMapping.defaultMapping` passes the key as the name when creating a `CircuitBreaker` so that `CircuitBreaker`s can have different names according to the key.
One thing I can think of is that we can perhaps provide a method that takes a prefix of the `CircuitBreaker`s, but I'm not sure it's worth though.

**Comment by trustin** [comment]
Hmm? `KeyedCircuitBreakerMapping.defaultMapping` feeds the host and IP address of the request to `CircuitBreaker.of(String)`, rather than an empty string.

**Comment by JunoJunho** [comment]
Oh yes, I misunderstood it.
Default circuit breaker gives host IP with specified port.
