### ISSUE TITLE
Client-side HAProxy support

### ISSUE THREAD

**Issue by trustin** [line/armeria#2589]
#2496 added client-side proxied connections via SOCKS4, SOCKS5 and HTTP CONNECT. We could add HAProxy support as well, by adding `ProxyType.PROXY` and implementing client-side HAProxy protocol codec. We may want to contribute the codec to Netty first.

/cc @jrhee17

**Comment by jrhee17** [comment]
lol... was already working on a netty PR, so I'll proceed with this 😄 
(https://github.com/jrhee17/netty/tree/haproxy-encoder)

**Comment by jrhee17** [comment]
So I actually became curious of what scenarios haproxy client-side support would be useful.

I actually think the only scenario client-side haproxy support might really be useful is in a multi-layered proxy structure where the original client address is relayed.

i.e.) Assuming a `client -> armeria server -> backend server` architecture, we may allow something like the following
```
protected HttpResponse doGet(ServiceRequestContext ctx, HttpRequest req) {
    WebClient client = WebClient.builder(H1C, server.httpEndpoint()).factory(clientFactory)
        .proxiedAddresses(ctx.proxiedAddresses())
        .responseTimeoutMillis(Long.MAX_VALUE).build();
     return HttpResponse.of(client.get("/"));
}
```


The problem is, for the correct proxy information to be propagated correctly, we need to guarantee an outgoing connection is always linked to the same incoming connection. This isn't true for armeria when HTTP/2 is enabled.

i.e.) when enabling HTTP/2, although connection#2 is opened with PROXY message for connection#1, any other client-side connection can still send a request proxied through connection#2.
```
client --connection#1--> armeria server --connection#2--> backend (proxy message for connection#1)
client --connection#3--> armeria server --connection#2--> backend (proxy message for connection#1)
client --connection#4--> armeria server --connection#2--> backend (proxy message for connection#1)
```

So I guess my question is
1) Did you have any other use-cases in mind which I hadn't thought of?
2) Your opinion of supporting relaying proxy messages like the above.

I also have written a very basic [POC](https://github.com/jrhee17/armeria/pull/3/files) in case you are curious of what kind of changes will happen.

**Comment by jrhee17** [comment]
I suppose alternatively, we may only allow client-side HAProxy for HTTP1 (although I'm not sure how this would be done..)
Anyways, I've opened a PR at netty upstream for those interested

**Comment by jrhee17** [comment]
Perhaps we also have the option to delegate this to the user
(Maybe he/she can create WebClient based on the proxied address)
