### ISSUE TITLE
KafkaAccessLogWriter Serialization?

### ISSUE THREAD

**Issue by OneCricketeer** [line/armeria#2617]
AFAICT, the producer instance is pre-configured for the AccessLogWriter. 

If that is that case, how is the message content really serialized? 

Possible ways, in order of increasing preference: Bytes? String? JSON? Thrift? Protobuf? Avro?

If it were a binary format, I think the key/value extractor functions need updated, right?

**Comment by trustin** [comment]
As far as I know, you can specify a serializer when you instantiate a `KafkaProducer`, so you can convert whatever value into a `byte[]`. It means you need to write some serializer that serializes a `RequestLog` into a `byte[]`. Internally, some of us use Protobuf while some others use JSON, but key-value extractors could be independent from serializer implementations. Make sense?

We may want to provide some out-of-the-box serializer implementations, but didn't receive many demands for them, maybe because it usually requires quite a bit of customization.

**Comment by cricket007** [comment]
Yeah, makes sense. So, in theory, anything Jackson based would work? https://github.com/FasterXML/jackson-dataformats-binary


I'm not familiar with any Thrift Kafka serializers out there, so seeing as that's the prevalent format here, might be worth adding.

Although, maybe not for access logs since those ought to be human readable.

**Comment by trustin** [comment]
Sorry I'm late, @OneCricketeer.

> So, in theory, anything Jackson based would work?

Yes. If you are serializing a Thrift message, you might want to use [ThriftJacksonModule](https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/latest/com/linecorp/armeria/common/thrift/ThriftJacksonModule.html).
