### ISSUE TITLE
Support unframed gRPC officially

### ISSUE THREAD

**Issue by trustin** [line/armeria#2645]
We currently support unframed gRPC requests only for the server side, primarily for DocService, but we got a few requests about making an unframed gRPC requests from the client side as well:

> Gary: I imagine, many people migrating to grpc will be facing this same issue. Allowing a way to call these services without the constraints required around ELB’s and HTTP/2 edge I think will definitely be helpful.
> @andrewoma: It's actually the whole reason I investigated Armeria in the first place
> Gary: Likewise

We could:

- Add support for unframed gRPC requests on the client side.
- Improve the efficiency of unframed gRPC requests on the server side, if possible.

**Comment by anuraaga** [comment]
Our client already supports grpc-web which works with HTTP/1 just fine. It's a better option than adding unframed to the client, as unframed gRPC is mainly to help migrate from json to gRPC - a server that is currently serving a JSON post API can use unframed gRPC to continue to serve it at the same time as clients switch to the real gRPC client. The reason the doc service uses unframed is since it predates our support of gRPC-web but will be good to switch at some point.

But I'm doubtful that even that really helps here. I don't know if anything has changed but I think Android devices only ever use upstream gRPC with okhttp since Netty doesn't work well on phone, and iOS is of course a different story.

**Comment by gary-lo** [comment]
This is awesome. Thanks @anuraaga for the context. I think we just need some documentation update, because it wasn't apparent that our clients supported grpc-web. Out of curiosity, given your test client supports grpc-web and it's on the JVM. Any ideas why it seems like there aren't any public projects that support grpc-web for Android?

**Comment by anuraaga** [comment]
I haven't heard of any client with official support for both Android and grpc-web. That being said, while people generally use okhttp-based clients on Android, Netty may work ok too, I don't know how much investigation that has ever really gotten - there was a time where it required Unsafe and didn't work at all if I remember correctly which is where Don't use Netty on Android became best practice but that should be fixed now. Definitely would require significant flag tweaking, in particular disabling buffer pooling but maybe worth taking a look, no promises that it works well though.

**Comment by anuraaga** [comment]
@trustin Can we go ahead and close this issue in favor of gRPC-web for HTTP/1 use case? Unframed gRPC is to allow migrating a server to gRPC before a legacy client. It's conceivable to migrate a client before a server, I don't think anyone would ever do that.

**Comment by trustin** [comment]
Thanks @anuraaga for advices and @gary-lo for reporting back. Let me close this issue.
