### ISSUE TITLE
New decorating client to manipulate HTTP request headers 

### ISSUE THREAD

**Issue by gotchazipc** [line/armeria#275]
An issue from #266. @trustin suggested to create a new <code>DecoratingClient</code> that can replace <code>ClientOptions.HTTP_HEADERS</code>option. 

```
clientBuilder.decorate(HttpRequest.class, HttpResponse.class,
        new HttpHeaderInjectingClientBuilder()
                .add(headerToAdd, value)
                .set(headerToReplace, value)
                .remove(headerToRemove)
                .set(headerToSet, (....) -> generate(...));
                .buildDecorator());
```
- How about naming the new decorator as <code>HttpHeaderManipulatingClient</code>? 
-  I can't see any other decorating client which has it's own builder class. Some existing pattern could be applied to build new client like this : 

```
ClientBuilder(...)
                .decorator(HttpRequest.class, HttpResponse.class,
                           HttpHeaderManipulatingClient.newDecorator(new HttpHeaderManipulatorBuilder()
                                   .add( ... ) 
                                   .set( ... ) 
                                   .remove( ...)
                                   .buildManipulator()
                .build() 
```
- I'm testing <code>remove(BiPredicate<AsciiString header, String value>)</code> to remove multiple headers with given condition. IMHO, the builder class doesn't need to have any more complex operations than simple add/set/remove, for now. 
- Allowing new decorator to add/set/remove 'any' header fields may break some requests. It would be helpful if we can re-use the black-list headers in HTTP_HEADERS option.

**Comment by trustin** [comment]
> How about naming the new decorator as `HttpHeaderManipulatingClient`?

SGTM

> I can't see any other decorating client which has it's own builder class.

How about `...Builder.newDecorator()`? https://github.com/line/armeria/pull/263/files#diff-137a843a5da81798a03a685a47fce620R431

> I'm testing remove(BiPredicate) to remove multiple headers with given condition. IMHO, the builder class doesn't need to have any more complex operations than simple add/set/remove, for now.

How about just adding a method `update(Consumer<? super HttpHeaders>)` so that a user can do whatever he or she wants to do?

> Allowing new decorator to add/set/remove 'any' header fields may break some requests. It would be helpful if we can re-use the black-list headers in HTTP_HEADERS option.

SGTM. Perhaps we could share it by moving it to `ArmeriaHttpUtil`?

**Comment by gotchazipc** [comment]
> How about just adding a method update(Consumer<? super HttpHeaders>) so that a user can do whatever he or she wants to do?

In fact, builder class has already <code>update</code> internally, as the base of other methods. Making it public is easy, but I think I should provide some _safe_ update() that reverts all changes to _black-listed_ headers for users. 
 
> Allowing new decorator to add/set/remove 'any' header fields may break some requests. It would be helpful if we can re-use the black-list headers in HTTP_HEADERS option.
> SGTM. Perhaps we could share it by moving it to ArmeriaHttpUtil?

While moving the black-list into <code>ArmeriaHttpUtil</code>, I found that the list does not contain 'content-length' and 'content-transfer-encoding' headers. Would it be safe if those headers are modified by client or decorator? DefaultHttpClient overwrites content-length for aggregated request message but seems to do nothing more.

**Comment by trustin** [comment]
> While moving the black-list into `ArmeriaHttpUtil`, I found that the list does not contain 'content-length' and 'content-transfer-encoding' headers. Would it be safe if those headers are modified by client or decorator? DefaultHttpClient overwrites content-length for aggregated request message but seems to do nothing more.

Because the content of a request/response is a stream, there's no way to determine if the 'content-length' set is correct or not before its headers are sent. We have to trust a user who sets it. i.e. we can't blacklist it.

WRT 'transfer-encoding' and other blacklisted headers, I guess we don't need to be overly restrictive on the headers a user sets, as long as it does not violate the specification. We already do some checks, filtering and manipulation to prevent unintended violation of the specification in `ArmeriaHttpUtil`.

Given that we are going to give a user a lot of freedom in header manipulation, how about letting a user do whatever he or she wants to do with the manipulator and filtering the bad headers out automatically during the conversion?

**Comment by trustin** [comment]
i.e. Forget about blacklists when implementing the manipulating client. Review the conversion methods in `ArmeriaHttpUtil` and implement additional filtering and manipulation if necessary.

**Comment by gotchazipc** [comment]
OK, let users have freedom to change everything with decorator. Actually, if we don't have to restrict the behaviors of manipulating client, the client code can be much simplified 😄

**Comment by trustin** [comment]
This has been resolved via `Clients.withHttpHeaders()` and `ClientRequestContext.HTTP_HEADERS` attribute. It's sad that your contribution was not accepted eventually, but I appreciate your effort, @gotchazipc
