### ISSUE TITLE
Question about SlidingWindowCounter

### ISSUE THREAD

**Issue by eunchan-kim** [line/armeria#2761]
Hi, I have a question about `SlidingWindowCounter` implementation.

FYI, I was making a circuit breaker with minimum request threshold = 2, failure rate = 0.1.
I expected the circuit to be open when first `FAILURE`(in the example below) event occurs, but it wasn't.

The reason was that `SlidingWindowCounter` (used by circuit breaker) does not include current event
when current bucket is replaced with next bucket. (when currentBucket.timestamp() + updateInterval < current ticker)
At that condition, current event (incremented in `nextBucket`) is not included in EventCount of `onEvent` method.

This is an example describing my issue.
Due to this issue, circuit was not opened for `FAILURE` (at timestampA) even though all conditions for circuit breaker was satisfied.

Timestamp of event | currentBucket.timestamp() + alpha | currentBucket.timestamp() + alpha2  ( < currentBucket.timestamp() + updateInterval) | timestampA | timestampB  ( < timestampA + updateInterval)
-- | -- | -- | -- | --
Event | SUCCESS | SUCCESS | FAILURE | SUCCESS
AS-IS onEvent result (EventCount) | null | null | EventCount.of(success = 2, failure = 0) | EventCount.of(success = 2, failure = 1)
AS-IS circuit | closed | closed | closed | closed
suggesting TO-BE (?) | null | null | EventCount.of(success = 2, failure = 1) | EventCount.of(success = 3, failure = 1)
TO-BE circuit | closed | closed | open | (when circuit is open, request will fail fast)

Could you guys take a look? 
I'd like to know if it's intended by SlidingWindowCounter design or it's need to be fixed.
Thank you!

**Comment by trustin** [comment]
I think it's an expected behavior. The calculation of event count (and thus success rate) should be done against the previous buckets only, excluding the current bucket, because the current bucket's state is not final yet. Let's say we have two buckets with the following counts:

- `previousBucket` with `success = 2, failure = 0`
- `currentBucket` with `success = 0, failure = 1`

Your suggestion is to take `currentBucket` into account, so that the circuit is open immediately because failure rate is `1/3 > 0.1`, but I'm not sure if it's a good idea because it can lead the circuit to open prematurely. Let's say we sent 10 successful requests before the `currentBucket` is moved to the reservoir, then the failure rate would be `1/13` which is less than `0.1`.

In your case, could the problem solved by increasing the number of buckets by decreasing `updateInterval`?

On the other hand, I think it may be nice if we allow a user to specify an alternative counting algorithm.

**Comment by eunchan-kim** [comment]
Thank you for the detailed explanation 😄 

>  but I'm not sure if it's a good idea because it can lead the circuit to open prematurely.

I also agree with this point.
So it can be summarized as 
`SlidingWindowCounter counts 'finalized' buckets only because otherwise it can lead to premature decision`.

> In your case, could the problem solved by increasing the number of buckets by decreasing updateInterval?

my use case was to open circuit by very small number of `FAILURE` responses (like `1`?)
and I think this can be configured by failureRate. 

Thank you for answer again! 👍
