### ISSUE TITLE
GHSA-35fr-h7jr-hh86 Credit Assignment

### ISSUE THREAD

**Issue by JLLeitschuh** [line/armeria#3113]
Hey Armeria Team,

GitHub recently rolled out a credit assignment system to GitHub.

Would you be willing to assign credit to me for disclosing this vulnerability to your team?
https://github.com/line/armeria/security/advisories/GHSA-35fr-h7jr-hh86

Thank you so much!

Cheers,
Jonathan Leitschuh

**Comment by trustin** [comment]
Hi @JLLeitschuh, we'd be happy to assign credit to you, but I don't know how to do so. Would you mind explaining a little bit on how to assign credit to someone in GitHub's vulnerability page? I don't see anything noticeable in the vulnerability page. Maybe it's not rolled out to all repositories? 🤔

**Comment by JLLeitschuh** [comment]
Hey @trustin 

If you click 'edit' on the advisory (top right), then you go to the bottom you should see 'add a user', type my username 'JLLeitschuh' and click the '+' button.

![Screen Shot 2020-10-16 at 9 54 22 AM](https://user-images.githubusercontent.com/1323708/96267249-94726200-0f95-11eb-8f61-df321c295f9d.png)

**Comment by trustin** [comment]
Unfortunately, GitHub doesn't let me edit the advisory saying 'This advisory is being reviewed by GitHub and can no longer be edited.' 🤔

**Comment by JLLeitschuh** [comment]
I've reached out to someone on GitHub staff to help out here.

**Comment by rschultheis** [comment]
👋  Hello from the Github CNA team.  @JLLeitschuh pinged me about this as  were discussing some unrelated stuff about advisory credits.

After taking a look, it seems this advisory was unfortunately stuck in a "locked" state due to a bug that has since been addressed.  Basically we changed our logic for locking/unlocking advisory editing and unfortunately it seems we neglected to migrate the data for a few advisories with pending cve requests.  The effect is they were permanently locked to editing.

I have manually unlocked this particular advisory so it should now be possible to add @JLLeitschuh or any other github user to the credits per the above instructions from Jonathan.

To be clear:  The only time an advisory is expected to be locked for editing is when a CVE Request is pending, and even then the expected behavior is it automatically unlocks 72 hours after the cve request is sent if GitHub does not respond with a cve assignment in that time window.   My personal opinion is we should not prevent edits at any time and potentially that behavior change will come this year.

Thanks for raising this @JLLeitschuh 🙇

**Comment by JLLeitschuh** [comment]
@trustin, can you follow up here? Just let me know if you need anything on my end! 😄 

Thanks @rschultheis!

**Comment by JLLeitschuh** [comment]
Friendly ping @trustin 😄

**Comment by trustin** [comment]
Sorry I'm late! Just added you to the Credits field. It seems like you need to accept it.

**Comment by JLLeitschuh** [comment]
Done! Thank you so much! 😄

It was a pleasure working with you on this issue.

**Comment by trustin** [comment]
Thanks a lot for your patience on this. Looking forward to your reports in the future, although no vulnerability would be the best :wink:
