### ISSUE TITLE
How to support non-HTTP RPC protocol in single port with gRPC

### ISSUE THREAD

**Issue by Zeymo** [line/armeria#3170]
Now we do some protocol migration from Customer-RPC-Protocol to gRPC, we want legacy protocol and gRPC shared logic and run in single port.

AFAIK Armeria is HTTP-based framework, our Customer-RPC-Protocol something like HTTP/1 (PlainText) and have magic code distinguish itself from other protocols

How can I inject  this protocol  into Armeria?

**Comment by trustin** [comment]
Hey @Zeymo, thanks for asking. If I understood correctly, your legacy protocol is HTTP-like but it's not HTTP. How much does it differ from HTTP/1? Could you give us some example? If it's just about introducing a new method name, it might not be extremely hard to support that, but otherwise it's currently not possible, although we want to add an extension point to support non-HTTP protocols as well.

**Comment by Zeymo** [comment]
@trustin thx for ur time

Request
`
MagicCode <Path>
header1:value1
header2:value2
`

Response
`
<statusCode>
header1:value1
header2:value2
`

body use Customer-Serialize, ProtoBuf,JSON,MessagePack etc.

It's almost like http besides MAGIC CODE

**Comment by trustin** [comment]
I see. Although very similar to HTTP, I think it cannot be handled by our HTTP stack because the headers have semantics incompatible to HTTP. However, please stay tuned - we'd like to add support for non-HTTP protocol sooner or later.
