### ISSUE TITLE
Duplicate injections when injecting value of parameters into a Kotlin data class object

### ISSUE THREAD

**Issue by Waynefn** [line/armeria#3454]
Suppose we define an annotated service method and data class like
```kotlin
    @Get("/example")
    fun getId(queries: ExampleQueries): String {
        return "example"
    }
```
```kotlin
data class ExampleQueries(
    @Param
    val name: String,

    @Param @Default
    val limit: Int?
)
```

A warning is printed when running the server 
`Ignoring a duplicate injection target '@Param("name")' at 'public final foo.model.ExampleQueries foo.model.ExampleQueries.copy(java.lang.String,int)'`

However, the internal doc shows duplicated fields like:
![image](https://user-images.githubusercontent.com/31786852/114666626-71085400-9d39-11eb-8d6b-f642117f5c3b.png)

I think this is not a bug but Armeria is incompatible with Kotlin data class.
(Version 1.3.0)

**Comment by trustin** [comment]
Thanks for reporting. We should fix this.

**Comment by KarboniteKream** [comment]
This issue can still be reproduced with Armeria 1.21.

With the following classes:
```kotlin
data class Request(
    @Param
    val application: String,
    @Param
    val topic: String,
    @Param
    val group: String,
)
```

```kotlin
@Get("/data")
fun getData(request: Request): String {
    return "Hello"
}
```

The errors are as follows:
```
c.l.a.i.s.a.AnnotatedBeanFactoryRegistry:
Ignoring a duplicate injection target '@Param("topic")'
at 'public final com.foo.Request com.foo.Request.copy(java.lang.String,java.lang.String,java.lang.String)'

c.l.a.i.s.a.AnnotatedBeanFactoryRegistry:
Ignoring a duplicate injection target '@Param("group")'
at 'public final com.foo.Request com.foo.Request.copy(java.lang.String,java.lang.String,java.lang.String)'
```

**Comment by ikhoon** [comment]
I figured out a bug in checking uniqueness using `TreeSet`.
https://github.com/line/armeria/blob/6b7b1b0b638f3d780f5910a133daf24902af8d93/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java#L116-L126

`uniqueResolverSet()` can't guarantee uniqueness because it always returns `-1` regardless of the input values. It should return a consistent value to make `TreeSet` compare the value with walking through the internal binary tree.
```java
@Test
void uniqueTest() {
    final TreeSet<Foo> uniques = new TreeSet<>((l, r) -> {
        final int result = l.name.compareTo(r.name);
        if (result == 0 && l.annotationType == r.annotationType) {
            return 0;
        } else {
            return -1;
        }
    });

    Foo fooA = new Foo("1", "A", Param.class);
    Foo fooB = new Foo("2", "B", Param.class);
    Foo fooC = new Foo("3", "C", Param.class);
    Foo fooA2 = new Foo("4", "A", Param.class);

    uniques.add(fooA);
    assertThat(uniques).hasSize(1);
    uniques.add(fooB);
    uniques.add(fooC);
    assertThat(uniques).hasSize(3);
    uniques.add(fooA2);
    // Fail to assert. The size of `uniques` is 4
    assertThat(uniques).hasSize(3);
}

static class Foo {
    private final String id;
    private final String name;
    private final Class<? extends Annotation> annotationType;

    Foo(String id, String name, Class<? extends Annotation> annotationType) {
        this.id = id;
        this.name = name;
        this.annotationType = annotationType;
    }
}
```

To fix the problem, we need to fix the compareTo function to:
```java
final TreeSet<Foo> uniques = new TreeSet<>((l, r) -> {
    final int result = l.name.compareTo(r.name);
    if (result == 0 && l.annotationType == r.annotationType) {
        return 0;
    } else {
        // return a different value depending of the inputs
        return result;
    }
});
```

Additionally, we may defer warning duplicated resolvers until checking all and log only when `redundant != resolvers.size()`
https://github.com/line/armeria/blob/6b7b1b0b638f3d780f5910a133daf24902af8d93/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java#L255-L265
