### ISSUE TITLE
Consider using re2j instead of Java standard regex package.

### ISSUE THREAD

**Issue by corona10** [line/armeria#3802]
https://github.com/google/re2j

Since re2j provides easy drop-in-replace for the Java standard regex package and provides linear time complexity.
it might be useful if it can improve performance enhancement.

I locally tested that most of the tests are passed with the replacement and some tests might need to be updated to follow behavior change.

Here is my **unreliable** local JMH test with a simple re2j replacement.
If the Armeria team decides to use re2j needs to test in an isolated environment.
(Sorry I don't have enough time to digging into more)

## re2j
````
Benchmark                             Mode  Cnt         Score         Error  Units
RoutersBenchmark.exactMatch          thrpt    5  10915472.983 ± 1845988.656  ops/s
RoutersBenchmark.exactMatch_wrapped  thrpt    5   8547327.975 ±  541627.186  ops/s
`````

## baseline
````
Benchmark                             Mode  Cnt        Score        Error  Units
RoutersBenchmark.exactMatch          thrpt    5  9143421.121 ± 892657.073  ops/s
RoutersBenchmark.exactMatch_wrapped  thrpt    5  7254068.046 ± 467207.801  ops/s
````

**Comment by ikhoon** [comment]
The benchmark numbers look attractive. 🏎

**Comment by anuraaga** [comment]
For reference since I don't think it's so commonly known, Java 9 made significant improvements to the builtin regex and does not have the possibility of exponential performance for patterns without backrefs

https://openjdk.java.net/jeps/8260688
https://bugs.openjdk.java.net/browse/JDK-8260688

It uses an NFA for these patterns, which isn't fundamentally different from approaches like re2 FWIU.

Either way, as long as `java.regex.Pattern` is exposed in the API, I don't think the regex engine can be changed. It would be too weird if a method `regex(Pattern)` behaved differently from `regex(String)`, nor does it seem nice to get the raw pattern from `Pattern` and process with a different engine.

https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java#L235

For the benchmarks, it seems the numbers are within the noise of each other. Which makes sense because they seem to test `exactMatch` - it shouldn't be using regex at all.

**Comment by corona10** [comment]
@anuraaga @ikhoon 

> For the benchmarks, it seems the numbers are within the noise of each other. Which makes sense because they seem to test exactMatch

Yeah, it can be, I reran the benchmark in a more clear environment.
Benchmark itself can be noise :(

`````
## re2j
Benchmark                             Mode  Cnt         Score         Error  Units
RoutersBenchmark.exactMatch          thrpt    5  12792786.669 ± 1420143.708  ops/s
RoutersBenchmark.exactMatch_wrapped  thrpt    5  11457026.526 ±   83597.683  ops/s

## baseline
Benchmark                             Mode  Cnt         Score        Error  Units
RoutersBenchmark.exactMatch          thrpt    5  12679578.212 ± 724865.433  ops/s
RoutersBenchmark.exactMatch_wrapped  thrpt    5  10654471.261 ± 133429.018  ops/s
`````

**Comment by ikhoon** [comment]
If there is no difference, let's keep `java.regex.Pattern`. Thanks to @corona10 for raising this issue. 
Please reopen this issue or file a new issue if you have any random ideas you want to discuss. 🙇‍♂️
