### ISSUE TITLE
Provide a utility class that extracts path and query params

### ISSUE THREAD

**Issue by trustin** [line/armeria#421]
Although we already have some of this functionality in `DynamicHttpService`, it would be useful to have a stand-alone utility class that is dedicated to path/query param extraction. For example:

```java
private static final PathParamExtractor paramExtractor = new PathParamExtractor("/{value}");

protected void doPost(ctx, req, res) {
    String value;
    value = ppe.extract(req, "value").orElse("");
    // or
    Map<String, String> values = ppe.extract(req); // Returns an empty map when not matching
    value = values.getOrElse("value", "");
    ...
}
```

and then we could reuse this in `DynamicHttpService` as well.

/cc @dongjinleekr

**Comment by trustin** [comment]
Fixed via #424

**Comment by anuraaga** [comment]
Does PathParamExtractor handle query params? I guess this issue is for path and query, and having a utility for query would be useful too

**Comment by trustin** [comment]
That's a good question. We could add query param support to this. WDYT, @lespinsideg @dongjinleekr ?

**Comment by lespinsideg** [comment]
How about add a new class like

```java
Map<String, String> values = QueryParamExtractor.extract("/some/url?q=1&r=2");
```

Or any idea?

**Comment by trustin** [comment]
@lespinsideg Sounds good to me. Perhaps we could also make it handle the query parameter in the POST content if applicable?

**Comment by anuraaga** [comment]
I think a QueryParamExtractor would be a thin layer on top of netty's ```QueryStringDecoder```. I use the latter a lot and it works fine, except the interface is quite annoying since it can only return lists, which may be null or empty, when the very standard use case of query params is singular. So I end up always writing a function that is basically implemented something like ```Iterables.getFirst(firstNonNull(decoder.getParam(param), ImmutableList.of()), null)```;

I think since query params are much simpler than path params, we could just add it to ```HttpRequest```? What do you think?
```
interafce HttpRequest {
  QueryParams queryParams()
}
```
where QueryParams offers ```get``` and ```getAll``` methods, that either eagerly or lazily decode the query string using ```QueryStringDecoder```.

**Comment by trustin** [comment]
@anuraaga Sounds good all in all, but shouldn't it be `CompletableFuture<QueryParams> params()` given that the content may have to be read?

**Comment by anuraaga** [comment]
Yep that sounds right :)
