### ISSUE TITLE
HttpJson Encoded Api call responds differently from actual gRPC service in certain cases

### ISSUE THREAD

**Issue by j-min5u** [line/armeria#4337]
[Replicated test case github](https://github.com/j-min5u/armeria-bug-report/tree/master)
In this testcase, http-json transcoded endpoint responds with 503 SERVICE_UNAVAILABLE when authenication via MyAuthenticator fails.
gRPC call responds normally with 401 UNAUTHENTICATED.

However, throwing _Status.UNAUTHENTICATED.asRuntimeException()_  in a HTTP-JSON transcoding service responded with 401 UNAUTHORIZED

The testcase uses a custom Authorizer and a custom annotation to decorate specific rpc methods with the Authorizer

**Comment by jrhee17** [comment]
Thanks, this looks like a bug 👍 

https://github.com/line/armeria/blob/8b0225ec63e231428276f30b92f8357eb7876b03/grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java#L184

The call flow is as follows:

- `HttpJsonTranscodingService` -> `GrpcDecoratingService`(contains the Authorizer) -> ... -> `FramedGrpcService`

`HttpJsonTranscodingService` assumes that the response it received is a framed grpc message. However, since the `Authorizer` returns a plain http response, `grpcStatusCode` is null and an NPE is thrown (which is never caught).

https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java#L184

This problem isn't limited to `Authorizer` usage, since there are other instances where a normal http message is returned as the response.

e.g.
https://github.com/line/armeria/blob/8b0225ec63e231428276f30b92f8357eb7876b03/grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java#L219-L225

To solve this, we may:
1) Determine whether the response is a framed grpc message. An easy way could be checking whether the header `grpc-status` exists in the response.
2) If the header doesn't exist, proxy the response without deframing.

**Comment by j-min5u** [comment]
May I give a try with the fix on this issue? 👀

**Comment by jrhee17** [comment]
Sure! Feel free to start experimenting on how to solve this issue.
I'll also look into the best way to solve this 🙏

**Comment by ikhoon** [comment]
> May I give a try fixing this issue? 👀

For sure! Let me explain detail of the gRPC service implementation and how to fix the problem.

- `GrpcDecoratingService` is a dynamic decorator set that applies HTTP decorators to an HTTP request and response.
- `HttpJsonTranscodingService` translate a HTTP REST/JSON request into a gRPC request.

Currently, a `GrpcDecoratingService` is wrapped by `HttpJsonTranscodingService`.
 TTP level decorators, in turn, work in the middle of gRPC services which causes your problem.
https://github.com/line/armeria/blob/d2f2a7097643aedb2f69b289aa5f83e89f4ba2c5/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L871-L879

To solve the problem, we need to move `GrpcDecoratingService` to the first service and make `GrpcDecoratingService` wrap `HttpJsonTranscodingService`
so that HTTP level decorators are applied before gRPC services.
```
GrpcDecoratingService -> HttpJsonTranscodingService -> FramedGrpcService
```
