### ISSUE TITLE
Send `Connection: close` header when it is received.

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4471]
If `Connection: close` is not set in HTTP/1.1 headers, we can assume the connection is persistent. 
If a client sends `Connection: close`, `HttpServerHandler` refuses accepting additional requests from the connection. 
But it does not send back `Connection: close` to the client. It would be fine in most cases because the client wanted to close the connection and it may close the connection regardless of the existence of `Connection: close`.
That being said, sending `Connection: close` clearly complies with the HTTP/1.1 protocol.

**Comment by jrhee17** [comment]
> HTTP/1.1 defines the "close" connection option for the sender to
   signal that the connection will be closed after completion of the
   response. For example,

       Connection: close

   in either the request or the response header fields indicates that
   the connection SHOULD NOT be considered `persistent' ([section 8.1](https://www.rfc-editor.org/rfc/rfc2616#section-8.1))
   after the current request/response is complete.

https://www.rfc-editor.org/rfc/rfc2616#section-14.10

So that other people reviewing the PR doesn't have to dig into the rfc.

**Comment by jrhee17** [comment]
Having said this, I'm curious why we want to do this at the cost of sending an extra number of bytes.

Were there any edge-cases that were failing due to not sending `Connection: close` from server-side?

**Comment by ikhoon** [comment]
> Were there any edge-cases that were failing due to not sending Connection: close from server-side?

No, it isn't. I realized Armeria doesn't send a `Connection: close` header while implementing Armeria backend for Play Framework. Anyway, sending "Connection: close` seems more common and correct behavior in HTTP/1.1 servers.
```sh
# Did not return "Connection: close"
curl --http1.1 https://www.google.com -I
curl --http1.1 https://facebook.com -I
curl --http1.1 https://github.com -I
# All servers sent back "Connection: close" header to the client
curl --http1.1 https://www.google.com -I -H "connection: close"
curl --http1.1 https://facebook.com -I -H "connection: close"
curl --http1.1 https://github.com -I -H "connection: close"
```
