### ISSUE TITLE
Add `GrpcCircuitBreakerRule`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4496]
If a `CircuitBreakerRule` is built for gRPC clients, users might want to get `grpc-status` to decide whether a call is a success or not. Normally, `grpc-status` exists in the HTTP trailers of a response. However, if a call is failed, it could be in the HTTP headers of a trailers-only response. It is a [transport-level protocol specification](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) and many users may not know the details.

If we add `GrpcCircuitBreakerRule` which inherits the existing `CircuitBreakerRule` and add `onGrpcStatus()`, users will be able to use circuit breaker with gRPC clients more easily.

**Comment by ikhoon** [comment]
@jrhee17 made a good idea to add `GrpcRetryRule`.

**Comment by Lincong** [comment]
Generally I think adding `GrpcCircuitBreakerRule` with a `onGrpcStatus` method is a great idea. 

However, it could be even better if the `GrpcCircuitBreakerRule` has a method `onGrpcTrailers(grpcTrailers: HttpHeaders)` where `grpcTrailers` is "trailers" in the context of gRPC. Specifically, `grpcTrailers` could be either HTTP headers if the response is "trailers-only" or HTTP trailers if the response has 3 parts (HTTP headers, body, and HTTP trailers).

This `onGrpcTrailers(grpcTrailers: HttpHeaders)` is more generally useful because users get access to the whole gRPC trailer which must contain gRPC status (as promised by the gRPC protocol specification). Another way to think about it would be: what if users want to set up their circuit-break conditions upon other information stored in gRPC trailers other than just gRPC status?

Let me know what you think. Thanks!

**Comment by ikhoon** [comment]
> it could be even better if the GrpcCircuitBreakerRule has a method onGrpcTrailers(grpcTrailers: HttpHeaders)

Agreed! In addition to `onGrpcStatus()`, `onGrpcTrailers()` would be a good extension method for `GrpcCircuitBreakerRule` and `GrpcRetryRule`.

**Comment by Lincong** [comment]
Thanks @ikhoon , I wonder when will this `GrpcCircuitBreakerRule` feature possibly be GA?

Just trying to get a sense of the timeline and you do not need to promise anything. Thanks!

**Comment by ikhoon** [comment]
Generally, we try to release a new version every month. However, we are snowed under to participate in LINE internal events, so the next version will be released in the middle of next month.

**Comment by trustin** [comment]
@Lincong [The PR for this issue](https://github.com/line/armeria/pull/4535) is up - let me know what you think.

**Comment by minwoox** [comment]
#4535 added `AbstractRuleBuilder.onGrpcTrailers()` which will be used instead of `GrpcCircuitBreakerRule`.
