### ISSUE TITLE
Add K8sEndpointGroup

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4497]
So that the client connects to the pods directly instead of through service proxy.

Of course, we can set up "Headless" Services and use `DnsEndpointGroup` for CSLB.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records

However, if so, users cannot use the service proxy anymore which means that other components that are not using Armeria have no way to balance the load unless they have the well-made equivalent of `DnsEndpointGroup`.

Related links:
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#get-read-the-specified-service
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#list-list-or-watch-objects-of-kind-pod
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodStatus

**Comment by ta7uw** [comment]
May I work on this issue?

**Comment by minwoox** [comment]
Of course. It's all yours. 😄 
Please, let me know if there's anything I can help with.

**Comment by ta7uw** [comment]
Is it ok that we create a new Gradle module (The module name is `k8s`)?

**Comment by ikhoon** [comment]
If it does not need third-party dependencies, I'm OK to add `K8sEndpointGroup` to `c.l.a.client.endoint.k8s` of core module. @ta7uw Do you have any reason to prefer a new module?

**Comment by minwoox** [comment]
I personally prefer adding a dedicated module for `K8sEndpointGroup` to encapsulate it (such as we do for Eureka even if it doesn't have any third-party dependencies), but I'm fine with adding it to the core module if:
- it doesn't need any third-party dependencies obviously.
- it needs a small number of classes.

**Comment by adiseshan** [comment]
I think that there are 2 options.
1. Use plain http calls to kubernetes api. (OR)
2. Use k8s sdk viz., https://github.com/kubernetes-client/java 

I understand from the above communication that, the team is not planning to use any third-party dependencies. Before the decision is made, I would kindly recommend to consider the above mentioned SDK too.

**Comment by minwoox** [comment]
Hi @adiseshan!
Thanks for the opinion. 😄 
Could you let us know why you recommend using the library, please?

**Comment by adiseshan** [comment]
I think we intended to query kubernetes API and retrieve the list of pods etc.,

The mentioned library contains many prebuilt classes to take care of authentication, watching a pod etc.,
Eg., https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/WatchExample.java

Though I have not used the below mentioned packages, 
`io.kubernetes.client.openapi`, contains many prebuild models in java. This can also be used instead of armeria maintaining models of kubernetes request/response/objects.

**Comment by minwoox** [comment]
Thanks for the explanation.
So you mean if we use the library, we do not have to reimplement the features that are provided by the library.
There are also advantages by not using the third-party library such as reducing the size, etc.
Of course, if it's too much work, we definitely need to use the library.
You might want to participate our conversation about this in Slack:
https://line-armeria.slack.com/archives/C1NGPBUH2/p1675075239795269

**Comment by ikhoon** [comment]
I agree that it is not practical to reinvent the wheel. But https://github.com/kubernetes-client/java depends on OkHttp client which would be weird since we already have our own HTTP client. Additionally, as @minwoox said, most Armeria users do not expect to see those transitive dependencies from Armeria modules.

If the protocol provided by Kubernetes is straightforward and solid what do you think of implementing the specification without relying on the kubernatetes java client?

**Comment by adiseshan** [comment]
I agree. Let us please consider developing with lesser dependencies. If there is too much of orchestration, kindly reconsider.
