### ISSUE TITLE
Defect: HttpTranscodingService fails to find descriptor for nested message fields

### ISSUE THREAD

**Issue by j-min5u** [line/armeria#4631]
On certain conditions, armeria server fails to start with this error message:
Descriptor for the type 'PROTO_MESSAGE_FULL_NAME' does not exist.
This happens when a nested message is used as a field type from another message
i.e)
```proto
message A {
    string name = 1;
    B b = 2;
    message B {
        string name = 1;
    }
}

message SomeARequest { // error when getting field b type Descriptor for this message
    A.B b = 1;
}
```
The problem is that when finding the descriptor from file (HttpJsonTranscodingService:L333), Descriptors#findMessageTypeByName is used to find the descriptor.
However, this method does not find nested types
``` java
/**
 * Find a message type in the file by name. Does not find nested types.
 *
 * @param name The unqualified type name to look for.
 * @return The message type's descriptor, or {@code null} if not found.
 */
public Descriptor findMessageTypeByName(String name)
```
resulting with exception and the server hangs without starting.

**Comment by ikhoon** [comment]
Had a chat with @hyangtack who worked the initial work for gRPC transcoding. While he handled some issues, he tried to find `Descriptor` indirectly with `.findMessageTypeByName()` rather than directly get it from `field.getMessageType()`.
https://github.com/line/armeria/blob/76c50fe8238525fab7180b51c0de8422e6526e13/grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java#L344-L363

 However, I didn't get any problems when using `field.getMessageType()`.
I checked that the result of `field.getMessageType()` and the lookup result of `.findMessageTypeByName()` are the same. We may replace the following code with `field.getMessageType()` without regressions. The existing test suite in gRPC passed with `field.getMessageType()`.

Would you like to send a PR with the workaround?

**Comment by j-min5u** [comment]
Thanks for sharing the details 😄 I'll send a PR along with a test case that replicates the exception with the current logic
