### ISSUE TITLE
SerializationFormat.isAccepted cannot handle "application/x-thrift; protocol=TJSON; charset=UTF-8" as MediaType parameters comparison maybe wrong

### ISSUE THREAD

**Issue by lovepoetry** [line/armeria#473]
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/MediaTypeSet.java#L233

`range.parameters()` (actual) and `candidate.parameters()` (required) have wrong argument order?

```java
    private static boolean matches(MediaType range, MediaType candidate) {
        // Similar to what MediaType.is(MediaType) does except that this one
        // compares the parameters case-insensitively and excludes 'q' parameter.
        return (WILDCARD.equals(range.type()) || range.type().equals(candidate.type())) &&
               (WILDCARD.equals(range.subtype()) || range.subtype().equals(candidate.subtype())) &&
               containsAllParameters(range.parameters(), candidate.parameters());
    }
```

**Comment by lovepoetry** [comment]
@trustin Could you take a look please?

**Comment by trustin** [comment]
The order of arguments is correct, but `charset` parameter has to be handled specially.

**Comment by lovepoetry** [comment]
I think `containsAllParameters (requiredParameters, actualParameters)` is a little confusing.
How should I understand the method's meaning?

`requiredParameters` contains all parameters of `actualParameters`?
If so, `requiredParameters[protocol,charset]` and `actualParameters[protocol]` should return true and we don't consider `charset` of any special case.

In addition, the word `required` and `actual` are not literally related to `contains`.
What do you think?

**Comment by trustin** [comment]
That's actually the opposite. `actualParameters` have to contain all `requiredParameters`. i.e. it checks if the 'actual' parameters contains all 'required' parameters. I agree that this can be confusing. Let me clean the code up so it's easier to understand. Thanks for suggestion.

> we don't consider charset of any special case.

We don't. I meant implementing so in a follow-up PR.

On the other hand, according to the JSON RFC:

> JSON text SHALL be encoded in Unicode. The default encoding is UTF-8.
>
> Since the first two characters of a JSON text will always be ASCII characters [RFC0020], it is possible to determine whether an octet stream is UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE) by looking at the pattern of nulls in the first four octets.

I'm not sure we need to accept the `charset` parameter at all given that TJSON or TTEXT uses JSON as its content format. What do you think? What was the reason you added the `charset` parameter to `application/x-thrift; protocol=TJSON`? Is there a client that adds it automatically?

**Comment by trustin** [comment]
Another option to fix this issue would be just adding `application/x-thrift; protocol=TJSON; charset=utf-8` and `application/x-thrift; protocol=TTEXT; charset=utf-8` to the supported media type list in `ThriftSerializationFormatProvider`. I think this is better than handling `charset` parameter specially because:

1. A user who implements a non-Thrift service with content-type negotiation might not want to perform charset conversion at all.
2. If the user if OK with charset conversion, s/he can always choose to remove the `charset` parameter from the `accept` header before calling `MediaType.match()`.

However, this change will not work for other non-textual Thrift serialization formats such as `application/x-thrift; protocol=TCOMPACT; charset=utf-8`. I think it makes sense because it's not UTF-8 at all.

@lovepoetry WDYT?
