### ISSUE TITLE
Add an option to extend the connection idle timeout when a server receives a PING frame.

### ISSUE THREAD

**Issue by trustin** [line/armeria#4794]
Currently, Armeria server doesn't take received PING frames into account when determining whether the current connection is idle or not. As a result, no matter how often a client sends an HTTP/2 PING frame, idle timeout will kick in if you didn't actually send the frames such as HEADERS and DATA.

People often get confused by this intended behavior, because they sometimes expect their connection will be kept alive as long as they send a PING frame before idle timeout kicks in. We conciously chose this behavior so we are not affected by a malicious client that keeps sending PING frames to keep the connection indefinitely, defeating the original purpose of idle timeout.

However, some users find it useful to keep the connection alive indefinitely, especially in trusted environment.

Action items (for both clients and servers):

- Update the documentation of `idleTimeout` and `pingInterval` to clarify its behavior and why `idleTimeout` doesn't treat PING frames as actual traffic.
- When specifying `idleTimeout`, accept an additional flag that tells Armeria whether to treat the received PING frames as traffic or not.

**Comment by rodolfobrunner** [comment]
I am one of those users that finds it helpful to keep the connection alive indefinitely between trusted services. My service is latency sensitive as it deals with authz, but doesn't see too much traffic yet. 

I started by trying to solve my connection problemfrom the client side and came across [this](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) which built certain expectations/assumptions.

My expectations were: 
- The grpc client only had one connection & multiplexing, assuming the client (trusted) is not misconfigured. So I could keep the connection open "indefinitely". 
-  The frequency for PINGs messages WITHOUT messages that would consist of a "minimum traffic" per client. (had to be careful with auto DDoS)
- PINGs without messages would naturally be phased out when we start to see more traffic, as the frames would be in the messages. 
- After a certain number of bad (either by time or number) PINGs the connection would be closed. 

With those expectations, I was confused about how to configure Armeria. 
Looking at `idleTimeout` java doc, i interpret that it corresponded to GRPC_ARG_KEEPALIVE_TIMEOUT_MS. From the behaviour / looking at the code,  `idleTimeout` is the time allowed for a connection to be open since the last message (not accounting for PINGs). Receiving `PING: ack=true` changed nothing in the behaviour. 

I believe that the explicit configuration of allow (Server) or emit (Server or Client) PINGs without messages to `true` expects additional configuration capabilities, such as: 
- GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS
- GRPC_ARG_HTTP2_MAX_PING_STRIKES
- GRPC_ARG_KEEPALIVE_TIMEOUT_MS

**Comment by Dogacel** [comment]
I am working on this:
- https://github.com/line/armeria/pull/4806
