### ISSUE TITLE
Close an HTTP/1.1 connection after delay

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4849]
Currently, if a `ReponseHeaders`, which contains `"connection: close"` headers, is sent, the server tries to close the connection immediately.
https://github.com/line/armeria/blob/b16bc8d926e3b4ebb07b86b66a09cd1126121574/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L94
This will make the sockets remain in the `TIME_WAIT` state.
We can probably avoid this by waiting a certain period of time so that clients do the active closing.

@trustin suggested waiting and closing the connection after writing an empty buffer:
`ctx.writeAndFlush(Unpooled.EMPTY_BUFFER).addListener(CLOSE);`

**Comment by echo304** [comment]
I'm pretty new to this kind of design/logic such as servers handling request and managing its connection.
Can you provide more context and guide how to 'wait for a certain period of time' without harming performance(blocking...etc..)

For example,  just invoking `Thread.sleep(WAIT_TIME)` looks crazy 😄 I believe there are more elegant way of handling and waiting from the view of server.

**Comment by minwoox** [comment]
@echo304 Oops, I missed your comment and apologize for that. 😓 
This issue has been assigned to a participant for our internal sprint.

**Comment by jrhee17** [comment]
### Background

The initiator of a socket close incurs `TIME_WAIT`. For this reason, in the client-server networking model it is generally recommended that the client-side closes the connection first.

However, in Armeria there are two ways of closing a connection from the server-side.

1. By calling `ServiceRequestContext#initiateConnectionShutdown`
  ```java
Server.builder()
      .service("/", (ctx, req) -> {
          if (req.headers().contains("should-close")) {
              ctx.initiateConnectionShutdown();
          }
          return HttpResponse.of(200);
      });
  ```
  - An `InitiateConnectionShutdown` event is sent over the channel pipeline which sets a flag
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L475
  - The flag is checked for each request/response completion, and the connection is closed if there are no in-flight requests
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L768-L786
2. By setting a `Connection: close` HTTP header
```java
Server.builder()
      .service("/", (ctx, req) -> {
          return HttpResponse.builder()
                             .header(HttpHeaderNames.CONNECTION, "close")
                             .status(200)
                             .build();
      });
```
  - A flag is set depending on the header set
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L153-L155
  - The channel is closed immediately after the response has been fully sent
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L95-L99

Note that this only pertains to HTTP1 since HTTP2 has its own graceful shutdown mechanism:
- https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java#L162

The above behavior can be observed from the following tests:
- https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/test/java/com/linecorp/armeria/server/HttpServerNoKeepAliveTest.java#L51
- https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/test/java/com/linecorp/armeria/server/InitiateConnectionShutdownTest.java#L258

### Handling this issue

I propose this issue be tackled in three steps:

1. A straightforward way to handle this issue is to add a delay to each location where `channel#close` occurs. Since an event loop is assigned to each channel, calling `EventExecutor#schedule` using the `ServiceRequestContext#eventLoop` with an arbitrary fixed delay should be good enough.
  - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L783
  - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L98
2. We probably want to unify the logic. The previous `Connection: close` semantic doesn't need to close connections immediately since we will wait a certain time period anyways. We can refactor/simplify so that the two locations are handled by common logic
3. Instead of using an arbitrary fixed delay, we can introduce a value in `Flags` so that users can configure the location of how much time the server should wait.
