### ISSUE TITLE
logback 1.4.8 breaks RequestScopedMdc

### ISSUE THREAD

**Issue by r3mariano** [line/armeria#5045]
https://github.com/qos-ch/logback/commit/ca7fbc7f4c1b1883092037ee4a662034586df07a / https://jira.qos.ch/browse/LOGBACK-1742 changed how the MDCAdapter is taken from at log time to at logger creation time. This means that if the logger object is created outside the request (e.g. a static logger object), the MDCAdapter attached to the object is not RequestScopedMdc.Adapter, and the MDC recorded at log time does not use RequestScopedMdc. A possible workaround is to create the logger at request time.

I'm unsure if this is something to fix in Armeria (is it possible to register this adapter earlier?), or something to fix in Logback.

**Comment by trustin** [comment]
Thanks for reporting! It's being fixed at #5079 :bow:

**Comment by ikhoon** [comment]
> I'm unsure if this is something to fix in Armeria (is it possible to register this adapter earlier?), or something to fix in Logback.

I had to use reflection to illegally access `LogbackMDCAdatper` in `LoggingContext` because Logback disallows overriding the MDCAdapter set before.
https://github.com/qos-ch/logback/blob/ca7fbc7f4c1b1883092037ee4a662034586df07a/logback-classic/src/main/java/ch/qos/logback/classic/LoggerContext.java#L412-L419

@r3mariano It would be worth opening an issue to Logback to override `LogbackMDCAdatper` with an API. Otherwise, the hacky workaround could be broken easily.

**Comment by r3mariano** [comment]
Thanks so much for the fix. I've emailed the logback-dev mailing list to see what they think.
