### ISSUE TITLE
The Debug popup in DocService reopens after collapsing items in the sidebar

### ISSUE THREAD

**Issue by KarboniteKream** [line/armeria#5047]
When running `:examples:thrift`, I can reproduce the following:

In the DocService, after opening the Debug popup for an API and testing a call, I can close it by clicking on the background (the URL remains the same). However, if I then try to collapse a service in the sidebar, the Debug menu reopens.

This does not seem to happen with annotated services.

https://github.com/line/armeria/assets/1769968/c63ede43-d018-4f6d-9cab-4e1fab34aa79

**Comment by Dogacel** [comment]
@trustin It seems like this is happening because we persist URL params after closing the debug form. We have two options:

1. Delete URL params after the Debug form is closed. (When you re-open the form it will be empty now)
2. Add a new URL param to toggle debug page.

I have implemented the second one. First one is much easier to implement but I don't like the idea of losing request body from URL when we navigate the page.

https://github.com/line/armeria/pull/5048

**Comment by trustin** [comment]
That was super fast, @Dogacel! :bow::+1:
