### ISSUE TITLE
Remove unimplemented configuration properties

### ISSUE THREAD

**Issue by trustin** [line/armeria#520]
For example, `ServerConfig.maxPendingRequests` is not implemented at all. We can add them when they are really implemented.

**Comment by hyangtack** [comment]
Will remove maxPendingRequests from ServerBuilder and ServerConfig classes, then find out the other not implemented configurations.

**Comment by hyangtack** [comment]
@trustin As you told me, `ServerConfig.maxConnections` is also not implemented. But what do you think about implementing that instead of removing? I think we can add a simple connection counting handler and let it close a new connection if the total number of connections exceed the configured value.

**Comment by trustin** [comment]
Fixed by #527
