### ISSUE TITLE
Provide debug hook point to trace original saml callback response

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#5401]
Motivations:
- When I integrate armeria server with our internal IdP using armeria-saml, sometimes faced some configuration miss on our side. Since current interface of armeria-saml ([ref](https://github.com/line/armeria/blob/armeria-1.26.4/saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java#L112)) does not expose `MessageContext`, I needed to fork https://github.com/line/armeria/blob/armeria-1.26.4/saml/src/main/java/com/linecorp/armeria/server/saml/HttpPostBindingUtil.java#L105 to see original xml message sent from idp to understand what is going on.

Suggestions:
- Passes already parsed MessageContext to loginFailed
- Make HttpPostBindingUtil to public to make it easy to decode at user side
- or provide a debug hook point to trace callback response on SamlAssertionConsumerFunction

**Comment by jrhee17** [comment]
### Background

Armeria provides a [saml](https://github.com/line/armeria/tree/main/saml) integration module, which allows users to easily set up a [Service Provider](https://en.wikipedia.org/wiki/Service_provider_(SAML)).

The basic flow is as follows:

1. A `SamlDecorator` checks if a request is authenticated or not
  - If it is already authenticated, then the request is served without an issue
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/saml/src/main/java/com/linecorp/armeria/server/saml/SamlDecorator.java#L109-L117
  - If it is not authenticated, a SAML redirect or form is returned depending on the configuration
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/saml/src/main/java/com/linecorp/armeria/server/saml/SamlDecorator.java#L149-L166
2. The user logs in to the [Identity Provider](https://en.wikipedia.org/wiki/Identity_provider_(SAML))
3. The Idp redirects the user to send a request to the [SamlService](https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java#L144)
  - The SAML [assertion](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language#Assertions) is validated for usage: 
    - https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java#L88

There is also an integration test which can be analyzed for this behavior:

ref: https://github.com/line/armeria/blob/main/saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java

### In terms of this issue

It can be difficult to debug why an assertion is not being processed correctly due to complex the inherent complexity of the SAML protocol.

I think for normal cases, deserializing SAML messages is not a big pain point since 1) the SAML library provides good enough logging, and 2) the SAML message format is relatively straightforward.

The bigger pain point is probably determining why a message refused to be processed. This would probably involve passing the parsed message in the following line:

https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java#L119

> Passes already parsed MessageContext to loginFailed

So in my opinion this suggestion by @imasahiro should be good enough for starters.

i.e.
```java
return ssoHandler.loginFailed(ctx, req, messageContext, e);
```

Note that this is simply how I would handle this issue if I were assigned - please feel free to think of any alternative ways to let users more easily debug this issue

**Comment by yeojin-dev** [comment]
I'm looking this issue. 👀
