### ISSUE TITLE
Add a repository (or repositories) to contain useful but specialized armeria-related functionality.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#65]
We will want the core armeria library to contain everything a normal production server would be expected to have, but we should also have a place we can put useful, but more specialized armeria-related libraries. Examples are armeria-spring or armeria-retrofit.

One idea is to have one more repository, armeria-extensions, which has a bunch of subprojects with each library. They can have independent version numbers and share some dependencies with armeria using a dependency pom.

**Comment by imasahiro** [comment]
@trustin suggested to me about multi-module project instead of creating instead of creating another repository.  @anuraaga WDYT?

Actually I'm working on reconstructing this repository to support multi-module project. My change is living in https://github.com/line/armeria/compare/master...imasahiro:multi

**Comment by anuraaga** [comment]
Yeah seems good to me

**Comment by anuraaga** [comment]
Also maybe time to switch to gradle for better multi-module support

**Comment by trustin** [comment]
+1 for switching to Gradle

**Comment by trustin** [comment]
Fixed via #300 :-)
