### ISSUE TITLE
URL encoded path mapping

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#756]
As described in [RFC3986](https://tools.ietf.org/html/rfc3986), a path component might be percent-encoded. If a regex path mapping has any reserved characters like `*` in its pattern and a request path is percent-encoded, the request might not be mapped to the path mapping.

**Comment by trustin** [comment]
According to our documentation, we explicitly stated all `path()` and `query()` methods return the string in the form as defined in RFC3986, which means they are expected to return a percent-encoded form.

So, instead of changing the contract of the existing API, we could add `PathMappingContext.decodedPath()` and make our `PathMapping` implementations use it instead of `PathMappingContext.path()`.

Similarly, how about adding `decodedPath()` to the following types?

- `RequestContext`
- `HttpHeaders`
- `HttpRequest`
- `AggregatedHttpMessage`
- `RequestLog`
- `PathMappingResult` (maybe not necessary?)

**Comment by trustin** [comment]
WRT annotated services, injected parameters should be decoded. :-)

**Comment by trustin** [comment]
Working on a fix
