### ISSUE TITLE
Do we have a way to seek http request at EndpointSelector?

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#832]
A user sometimes want to write a LB using in comming http request body.
To achive this, we can choose 2 way. First one is writing a HttpService that proxies a request to backend servers. And another one is using `EndpointSelector`.

If a user write such kind of `EndpointSelector` (see below code), When an `EndpointSelector` call `HttpRequest#aggregate` to retrieve actual http request, it causes `HttpRequest` subscription multiple times even if using `HttpRequestDuplicator` because HttpRequestDuplicator is also subscribes `HttpRequest` as well.

```java
class MyEndpointSelector implements EndpointSelector {
    private final EndpointGroup endpointGroup;

    @Override
    public CompletableFuture<Endpoint> select(ClientRequestContext ctx) {
        HttpRequest request = ctx.request();
        List<Endpoint> endpoints = endpointGroup.endpoints();
        // Following `aggregate` will cause multiple subscription because 
        // HttpClientDelegate#execute will subscribe as well.
        return request.aggregate()
                      .thenApply(message -> endpoints.get(message.content().toStringAscii()
                                                                 .hashCode() % endpoints.size()));
    }
}
```

The question is, what is the correct way to retrieve a http request body from HttpRequest at EndpointSelector?

**Comment by trustin** [comment]
Ideally the caller of `select(ctx)` would wrap the request with `HttpRequestDuplicator` so that the request consumed by the `EndpointSelector` is actually a duplicate. Not all `EndpointSelector` will need to check the content, so there should be a way for `EndpointSelector` to tell the caller whether it needs request duplication.

**Comment by trustin** [comment]
A workaround would be to write a decorator that duplicates the original `HttpRequest` and defers the delegation until the content is ready. When the content is ready, the decorator could set some special attribute in the `RequestContext` so that `EndpointSelector` picks it up.

This way, we didn't actually need to make `EndpointSelector` asynchronous at all. Hmm.

**Comment by trustin** [comment]
> Using `HttpRequestDuplicator`

If you want the complete content, you don't even need to use `HttpRequestDuplicator`. Just aggregate it and then produce a new `HttpRequest` using `AggregatedHttpMessage.toHttpRequest()`.

**Comment by trustin** [comment]
Continuing the discussion at #833
