### ISSUE TITLE
ArmeriaHttpUtil.toArmeria breakes cookie into linked list entry which will lead only the first cookie entry can be obtained

### ISSUE THREAD

**Issue by southernkasaist** [line/armeria#930]
Netty's `DefaultHeaders` will only get the value of first entry after head node:
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L117

But in armeria's header conversion, value of cookie header is broken into linked list entries.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java#L329

This will lead armera's cookie can only obtain the first cookie entry's value.

Example:
```
cookie: a=1; b=2;

But only a=1 will be obtained from HttpRequest#headers().get("cookie").
```

**Comment by lovepoetry** [comment]
@trustin 
Related change: https://github.com/line/armeria/pull/929

**Comment by anuraaga** [comment]
I haven't tried it myself but what if you use getAll?

Though admittedly not getting the raw string the client sent when calling get is confusing behavior.

**Comment by southernkasaist** [comment]
`getAll` is able to obtain the whole cookie kv pairs.
However, the return value of `headers().get()` had a breaking change which was result in critical bug in our application.

So I concern the following questions:
- Armeria was wrong before this change?
- The usage of `get` is wrong in our code?

**Comment by southernkasaist** [comment]
Seems that our usage of `get` wasn't following the document of netty...

https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/Headers.java#L38
```
    /**
     * Returns the value of a header with the specified name. If there is more than one value for the specified name,
     * the first value in insertion order is returned.
     *
     * @param name the name of the header to retrieve
     * @return the first header value if the header is found. {@code null} if there's no such header
     */
    V get(K name);
```

**Comment by anuraaga** [comment]
Looking at the referenced RFC

https://tools.ietf.org/html/rfc7540#section-8.1.2.5

The header must be concatenated when returning to a generic http server context, which probably applies to armeria. My feeling is that this is purely a protocol performance implementation detail, not a logic change so exposing users to it is a bug (and indeed seems like it could be quite painful if triggered :( )

So I propose moving that conversion to when converting armeria headers back to Netty http/2 headers rather than when reading http/1 headers. @trustin, what do you think?

**Comment by trustin** [comment]
#931 should fix this issue. Please review.
