### ISSUE TITLE
Make use of @Nonnull annotation

### ISSUE THREAD

**Issue by trustin** [line/armeria#943]
We currently assume all return values and parameters are non-null unless it's annotated with `@Nullable` explicitly. However, some languages or validation frameworks seem to expect the explicit use of `@Nonnull` annotations.

It would be great if we could apply some compiler plugin to automatically annotate all return types, parameters and fields with `@Nonnull`.

**Comment by anuraaga** [comment]
For reference, found that checker framework doesn't expect use of `@NonNull` since it's the default. But for consuming libraries it does seem like it'd be nice to automatically add it during the build

https://checkerframework.org/manual/#null-defaults

**Comment by kojilin** [comment]
and we can use `@javax.annotation.ParametersAreNonnullByDefault`?

https://youtrack.jetbrains.com/issue/KT-10942
https://medium.com/square-corner-blog/non-null-is-the-default-58ffc0bb9111

**Comment by trustin** [comment]
@kojilin Thanks for the info! What about return types?

**Comment by kojilin** [comment]
We can define our own annotation? like spring's one(`@NonNullApi`). And kotlin's spec should follow it. 

--
But not really familiar how IDE/tool will help checking, just showing in compilation output?

**Comment by tobias-** [comment]
I can only interpret "methods" in the following as meaning return value from methods. There are no nullable methods-references in neither kotlin nor java. In Kotlin there are functions, but seems farfetched. Disadvantage is that every package needs a file like that.

`
Annotation @ParametersAreNonnullByDefault gives the developer an option to define that for a given
class or package all the elements (methods, parameters, fields and variables) have @NotNull
semantic, unless they are explicitly annotated with the @Nullable annotation.
`

--

Marking the api with these won't do much for those developing armeria, but will help when those using the API, especially in Kotlin. Reducing the number of unncessary if (x != null) leaves cleaner code.

For Kotlin, using `@Nonnull` actually changes the return type from XXX! (state is unknown and this is the default when communicating with java code) to XXX(never nullable).

XXX! is something that should really be avoided in Kotlin and you can't even declare a variable as such. The way to fix it is to add plenty of !!(explicitly not null), which looks bad. The reason they picked !! is probably because it means you're screaming.

**Comment by tobias-** [comment]
@trustin Thanks. As I said in slack, this works for me with both parameters and results. Unfortunately I only warnings, but I'm inclined to believe that's because of a decision by Kotlin.

Either way, thanks!
